/**
 * 종목 사전 — 한글 종목명을 영문 사명으로.
 *
 * ── 왜 필요한가 ─────────────────────────────────────────────────
 * `/v1/research` 가 `subject: "삼성전자"` 를 내보낸다. **영문 API 인데 값이 한글이다.**
 * 해외 개발자가 그대로 못 쓴다. 기관명은 정규화했고(institutions.mjs) 종목이 남았다.
 *
 * ── 2,782개를 다 하지 않는다. 커버리지 순으로 한다 ──────────────
 * 아카이브에 종목이 2,782개인데 **응답 빈도가 극단적으로 쏠려 있다.**
 *
 *   상위   50개 → 전체 리포트의 29.5%
 *   상위  100개 → 45.2%
 *   상위  200개 → 63.2%
 *   상위  500개 → 83.6%
 *   상위 1000개 → 92.8%
 *
 * **상위 몇백 개만 해도 대부분의 응답이 영문으로 나간다.** 나머지는 `null` 로 두고,
 * DART 인증키가 나오면 `corpCode.xml` 의 `corp_eng_name` 으로 한 번에 채운다.
 * (그때 이 파일은 「손으로 확인한 것」으로 남고 자동 채움이 그 위에 얹힌다)
 *
 * ── 지어내지 않는다 ─────────────────────────────────────────────
 * 확신하지 못하는 이름은 **넣지 않는다.** 사전에 없으면 `null` 이 나가고,
 * 그것이 「아직 안 했다」는 정직한 신호다. 그럴듯한 영문명을 지어내면
 * 데이터 상품으로서 끝난다(api.mjs 설계원칙 2).
 *
 * ⚠ **공식 표기를 쓴다.** 회사가 스스로 쓰는 철자가 정답이다 —
 *   SK hynix(소문자 h) · NCSOFT(전부 대문자) · AMOREPACIFIC(붙여쓰기).
 *   보기 좋게 고치면 그건 우리가 만든 이름이지 그 회사 이름이 아니다.
 */

/**
 * 한글 종목명 → 영문 사명.
 * 빈도순으로 정렬해 두었다. **위쪽이 응답에 자주 나오는 것**이다.
 */
export const SUBJECTS = {
  /* ── 상위 50 (전체의 29.5%) ─────────────────────────────── */
  삼성전자: 'Samsung Electronics',
  LG전자: 'LG Electronics',
  삼성전기: 'Samsung Electro-Mechanics',
  SK하이닉스: 'SK hynix',
  NAVER: 'NAVER',
  LG이노텍: 'LG Innotek',
  현대차: 'Hyundai Motor',
  엔씨소프트: 'NCSOFT',
  SK텔레콤: 'SK Telecom',
  카카오: 'Kakao',
  KT: 'KT',
  LG유플러스: 'LG Uplus',
  현대모비스: 'Hyundai Mobis',
  삼성SDI: 'Samsung SDI',
  CJ제일제당: 'CJ CheilJedang',
  아모레퍼시픽: 'AMOREPACIFIC',
  현대제철: 'Hyundai Steel',
  KB금융: 'KB Financial Group',
  현대건설: 'Hyundai E&C',
  'KT&G': 'KT&G',
  신한지주: 'Shinhan Financial Group',
  기아: 'Kia',
  POSCO홀딩스: 'POSCO Holdings',
  LG화학: 'LG Chem',
  하나금융지주: 'Hana Financial Group',
  삼성물산: 'Samsung C&T',
  SK이노베이션: 'SK Innovation',
  LG생활건강: 'LG H&H',
  기업은행: 'Industrial Bank of Korea',
  우리금융지주: 'Woori Financial Group',
  삼성화재: 'Samsung Fire & Marine Insurance',
  삼성생명: 'Samsung Life Insurance',
  한국전력: 'Korea Electric Power',
  'S-Oil': 'S-Oil',
  롯데케미칼: 'Lotte Chemical',
  대한항공: 'Korean Air',
  GS건설: 'GS E&C',
  대우건설: 'Daewoo E&C',
  현대글로비스: 'Hyundai Glovis',
  한국조선해양: 'Korea Shipbuilding & Offshore Engineering',
  삼성중공업: 'Samsung Heavy Industries',
  두산에너빌리티: 'Doosan Enerbility',
  한화에어로스페이스: 'Hanwha Aerospace',
  셀트리온: 'Celltrion',
  삼성바이오로직스: 'Samsung Biologics',
  유한양행: 'Yuhan',
  한미약품: 'Hanmi Pharmaceutical',
  녹십자: 'GC Biopharma',
  대웅제약: 'Daewoong Pharmaceutical',
  종근당: 'Chong Kun Dang Pharmaceutical',

  /* ── 그 다음 (누적 45%대) ───────────────────────────────── */
  SK: 'SK',
  LG: 'LG',
  두산: 'Doosan',
  한화: 'Hanwha',
  GS: 'GS',
  CJ: 'CJ',
  효성: 'Hyosung',
  코오롱인더: 'Kolon Industries',
  금호석유: 'Kumho Petrochemical',
  한솔케미칼: 'Hansol Chemical',
  OCI: 'OCI',
  후성: 'Foosung',
  일진머티리얼즈: 'Iljin Materials',
  에코프로비엠: 'EcoPro BM',
  포스코퓨처엠: 'POSCO Future M',
  엘앤에프: "L&F",
  천보: 'Chunbo',
  솔브레인: 'Soulbrain',
  동진쎄미켐: 'Dongjin Semichem',
  원익IPS: 'Wonik IPS',
  주성엔지니어링: 'Jusung Engineering',
  피에스케이: 'PSK',
  테스: 'TES',
  유진테크: 'Eugene Technology',
  케이씨텍: 'KC Tech',
  리노공업: 'Leeno Industrial',
  이오테크닉스: 'EO Technics',
  한미반도체: 'Hanmi Semiconductor',
  DB하이텍: 'DB HiTek',
  LX세미콘: 'LX Semicon',
  실리콘웍스: 'Silicon Works',
  네패스: 'Nepes',
  하나마이크론: 'Hana Micron',
  SFA반도체: 'SFA Semicon',
  덕산네오룩스: 'Duk San Neolux',
  이녹스첨단소재: 'Innox Advanced Materials',
  대덕전자: 'Daeduck Electronics',
  심텍: 'Simmtech',
  비에이치: 'BH',
  인터플렉스: 'Interflex',
  삼성증권: 'Samsung Securities',
  미래에셋증권: 'Mirae Asset Securities',
  NH투자증권: 'NH Investment & Securities',
  키움증권: 'Kiwoom Securities',
  한국금융지주: 'Korea Investment Holdings',
  메리츠금융지주: 'Meritz Financial Group',
  DB손해보험: 'DB Insurance',
  현대해상: 'Hyundai Marine & Fire Insurance',
  BNK금융지주: 'BNK Financial Group',
  JB금융지주: 'JB Financial Group',
  DGB금융지주: 'DGB Financial Group',

  /* ── 유통·소비재·통신·콘텐츠 ───────────────────────────── */
  이마트: 'E-Mart',
  롯데쇼핑: 'Lotte Shopping',
  신세계: 'Shinsegae',
  현대백화점: 'Hyundai Department Store',
  BGF리테일: 'BGF Retail',
  GS리테일: 'GS Retail',
  오리온: 'Orion',
  농심: 'Nongshim',
  롯데칠성: 'Lotte Chilsung Beverage',
  하이트진로: 'HiteJinro',
  오뚜기: 'Ottogi',
  삼양식품: 'Samyang Foods',
  동원F앤B: 'Dongwon F&B',
  매일유업: 'Maeil Dairies',
  빙그레: 'Binggrae',
  한국콜마: 'Kolmar Korea',
  코스맥스: 'COSMAX',
  클리오: 'CLIO',
  애경산업: 'AEKYUNG Industrial',
  하이브: 'HYBE',
  JYP엔터테인먼트: 'JYP Entertainment',
  에스엠: 'SM Entertainment',
  와이지엔터테인먼트: 'YG Entertainment',
  스튜디오드래곤: 'Studio Dragon',
  'CJ ENM': 'CJ ENM',
  넷마블: 'Netmarble',
  크래프톤: 'KRAFTON',
  펄어비스: 'Pearl Abyss',
  카카오게임즈: 'Kakao Games',
  위메이드: 'WEMADE',
  더블유게임즈: 'DoubleUGames',
  컴투스: 'Com2uS',
  데브시스터즈: 'Devsisters',

  /* ── 자동차·부품·조선·기계 ─────────────────────────────── */
  한온시스템: 'Hanon Systems',
  만도: 'HL Mando',
  현대위아: 'Hyundai WIA',
  에스엘: 'SL Corporation',
  한국타이어앤테크놀로지: 'Hankook Tire & Technology',
  넥센타이어: 'Nexen Tire',
  금호타이어: 'Kumho Tire',
  HD현대중공업: 'HD Hyundai Heavy Industries',
  한화오션: 'Hanwha Ocean',
  HMM: 'HMM',
  팬오션: 'Pan Ocean',
  현대엘리베이터: 'Hyundai Elevator',
  두산밥캣: 'Doosan Bobcat',
  HD현대인프라코어: 'HD Hyundai Infracore',
  LIG넥스원: 'LIG Nex1',
  한국항공우주: 'Korea Aerospace Industries',
  현대로템: 'Hyundai Rotem',

  /* ── 소재·에너지·건설 ──────────────────────────────────── */
  고려아연: 'Korea Zinc',
  풍산: 'Poongsan',
  영풍: 'Young Poong',
  한솔제지: 'Hansol Paper',
  무학: 'Muhak',
  '쌍용C&E': 'Ssangyong C&E',
  한일시멘트: 'Hanil Cement',
  아세아시멘트: 'Asia Cement',
  삼표시멘트: 'Sampyo Cement',
  한전KPS: 'KEPCO Plant Service & Engineering',
  한국가스공사: 'Korea Gas',
  지역난방공사: 'Korea District Heating',
  E1: 'E1',
  SK가스: 'SK Gas',
  DL이앤씨: 'DL E&C',
  HDC현대산업개발: 'HDC Hyundai Development',
  태영건설: 'Taeyoung E&C',
  금호건설: 'Kumho E&C',
  /* ── 2차 보강 (2026-08-03) — 커버리지 순으로 골랐다 ─────── */
  LG디스플레이: 'LG Display',
  LG에너지솔루션: 'LG Energy Solution',
  호텔신라: 'Hotel Shilla',
  CJ대한통운: 'CJ Logistics',
  POSCO: 'POSCO',
  한화솔루션: 'Hanwha Solutions',
  기아차: 'Kia',
  제일기획: 'Cheil Worldwide',
  'F&F': 'F&F',
  'JYP Ent.': 'JYP Entertainment',
  삼성에스디에스: 'Samsung SDS',
  'CJ CGV': 'CJ CGV',
  파라다이스: 'Paradise',
  HL만도: 'HL Mando',
  신세계인터내셔날: 'Shinsegae International',
  강원랜드: 'Kangwon Land',
  'LS ELECTRIC': 'LS ELECTRIC',
  포스코인터내셔널: 'POSCO International',
  한섬: 'Handsome',
  '삼성E&A': 'Samsung E&A',
  코웨이: 'Coway',
  한국항공우주산업: 'Korea Aerospace Industries',
  두산퓨얼셀: 'Doosan Fuel Cell',
  현대오토에버: 'Hyundai AutoEver',
  카카오뱅크: 'KakaoBank',
  카카오페이: 'Kakao Pay',
  'SKC': 'SKC',
  'SK바이오팜': 'SK Biopharmaceuticals',
  'SK스퀘어': 'SK Square',
  'HD한국조선해양': 'HD Korea Shipbuilding & Offshore Engineering',
  세아베스틸: 'SeAH Besteel',
  영원무역: 'Youngone',
  휠라홀딩스: 'FILA Holdings',
  현대百: 'Hyundai Department Store',
  롯데정밀화학: 'Lotte Fine Chemical',
  대한유화: 'Korea Petrochemical Ind.',
  케이카: 'K Car',
  아시아나항공: 'Asiana Airlines',
  제주항공: 'Jeju Air',
  티웨이항공: "T'way Air",
  진에어: 'Jin Air',

  /* ── 3차 보강 (2026-08-03) — 미커버 상위 120개 ─────────────
     ⚠ 지금은 없어진 사명도 그대로 둔다. 아카이브에 그 이름으로 남아 있고,
        2014년 리포트를 2026년 사명으로 바꿔 부르면 그건 기록이 아니라 왜곡이다.
        (대우조선해양 → 한화오션, 대림산업 → DL E&C 등) */
  한세실업: 'Hansae',
  한화생명: 'Hanwha Life Insurance',
  삼성엔지니어링: 'Samsung Engineering',
  현대미포조선: 'HD Hyundai Mipo',
  대림산업: 'Daelim Industrial',
  한샘: 'Hanssem',
  SK네트웍스: 'SK Networks',
  롯데하이마트: 'Lotte Hi-Mart',
  HK이노엔: 'HK inno.N',
  이노션: 'Innocean Worldwide',
  효성중공업: 'Hyosung Heavy Industries',
  하나투어: 'Hana Tour',
  SBS: 'SBS',
  LS: 'LS Corp',
  씨에스윈드: 'CS Wind',
  HD현대일렉트릭: 'HD Hyundai Electric',
  대우조선해양: 'Daewoo Shipbuilding & Marine Engineering',
  에이피알: 'APR',
  GKL: 'Grand Korea Leisure',
  한국타이어: 'Hankook Tire',
  세아베스틸지주: 'SeAH Besteel Holdings',
  현대홈쇼핑: 'Hyundai Home Shopping',
  GS홈쇼핑: 'GS Home Shopping',
  한화시스템: 'Hanwha Systems',
  효성티앤씨: 'Hyosung TNC',
  웹젠: 'Webzen',
  코스메카코리아: 'Cosmecca Korea',
  스카이라이프: 'KT SkyLife',
  SK아이이테크놀로지: 'SK IE Technology',
  서울반도체: 'Seoul Semiconductor',
  삼성카드: 'Samsung Card',
  롯데웰푸드: 'Lotte Wellfood',
  CJ프레시웨이: 'CJ Freshway',
  고영: 'Koh Young Technology',
  LX인터내셔널: 'LX International',
  해성디에스: 'Haesung DS',
  'CJ E&M': 'CJ E&M',
  네오위즈: 'Neowiz',
  덴티움: 'Dentium',
  NHN: 'NHN',
  롯데관광개발: 'Lotte Tour Development',
  한전기술: 'KEPCO Engineering & Construction',
  현대중공업: 'HD Hyundai Heavy Industries',
  대상: 'Daesang',
  한화손해보험: 'Hanwha General Insurance',
  한화케미칼: 'Hanwha Chemical',
  에스티팜: 'ST Pharm',
  에스원: 'S-1 Corporation',
  더존비즈온: 'Douzone Bizon',
  클래시스: 'Classys',
  두산인프라코어: 'Doosan Infracore',
  CJ오쇼핑: 'CJ O Shopping',
  바텍: 'Vatech',
  파트론: 'Partron',
  효성첨단소재: 'Hyosung Advanced Materials',
  셀트리온헬스케어: 'Celltrion Healthcare',
  NHN엔터테인먼트: 'NHN Entertainment',
  아모레G: 'Amorepacific Group',
  LG상사: 'LG International',
  이수페타시스: 'Isu Petasys',
  인텔리안테크: 'Intellian Technologies',
  동아에스티: 'Dong-A ST',
  파마리서치: 'Pharma Research',
  메디톡스: 'Medytox',
  게임빌: 'Gamevil',
  화승엔터프라이즈: 'Hwaseung Enterprise',
  롯데푸드: 'Lotte Foods',
  세아제강: 'SeAH Steel',
  모두투어: 'Mode Tour',
  '동원F&B': 'Dongwon F&B',
  아프리카TV: 'AfreecaTV',
  제이콘텐트리: 'Jcontentree',
  디어유: 'DearU',
  'S&T모티브': 'S&T Motiv',
  솔루스첨단소재: 'Solus Advanced Materials',
  씨젠: 'Seegene',
  우리은행: 'Woori Bank',
  현대산업: 'Hyundai Development Company',
  RFHIC: 'RFHIC',
  콘텐트리중앙: 'Contentree JoongAng',
  SK머티리얼즈: 'SK Materials',
  롯데렌탈: 'Lotte Rental',
  솔루엠: 'Solum',
  아이센스: 'i-SENS',
  KH바텍: 'KH Vatec',
  로엔: 'Loen Entertainment',
  제이브이엠: 'JVM',
  유니드: 'Unid',
  티씨케이: 'Tokai Carbon Korea',
  뷰웍스: 'Vieworks',
  포스코케미칼: 'POSCO Chemical',
  코리안리: 'Korean Re',
  휴젤: 'Hugel',
  한라홀딩스: 'Halla Holdings',
  아모텍: 'Amotech',
  SK오션플랜트: 'SK Oceanplant',
  롯데에너지머티리얼즈: 'Lotte Energy Materials',
  대원제약: 'Daewon Pharmaceutical',
  에스에프에이: 'SFA Engineering',
  알테오젠: 'Alteogen',
  씨앤씨인터내셔널: 'C&C International',
  동부화재: 'Dongbu Insurance',
  ISC: 'ISC',
  SGC에너지: 'SGC Energy',
  동양생명: 'Tongyang Life Insurance',
  KCC: 'KCC',
  카페24: 'Cafe24',
  엠씨넥스: 'MCNEX',
  디오: 'Dio Implant',
  경동나비엔: 'Kyungdong Navien',
  원익머트리얼즈: 'Wonik Materials',
  OCI홀딩스: 'OCI Holdings',
  시프트업: 'Shift Up',
  인바디: 'InBody',
  동성화인텍: 'Dongsung Finetec',
  미래에셋대우: 'Mirae Asset Daewoo',
  SOOP: 'SOOP',
  비에이치아이: 'BHI',
  LS산전: 'LSIS',
  서진시스템: 'Seojin System',

  /* ── 4차 보강 (2026-08-03) — 미커버 상위 130개 ───────────── */
  HD현대건설기계: 'HD Hyundai Construction Equipment',
  오스템임플란트: 'Osstem Implant',
  원익QnC: 'Wonik QnC',
  한국철강: 'Korea Iron & Steel',
  펌텍코리아: 'Pum-Tech Korea',
  대교: 'Daekyo',
  쏠리드: 'Solid',
  케이엠더블유: 'KMW',
  이노와이어리스: 'Innowireless',
  동국제강: 'Dongkuk Steel',
  SNT모티브: 'SNT Motiv',
  한올바이오파마: 'HanAll Biopharma',
  신세계푸드: 'Shinsegae Food',
  두산중공업: 'Doosan Heavy Industries & Construction',
  태광: 'Taekwang',
  웅진씽크빅: 'Woongjin ThinkBig',
  메리츠화재: 'Meritz Fire & Marine Insurance',
  아이에스동서: 'IS Dongseo',
  iM금융지주: 'iM Financial Group',
  한글과컴퓨터: 'Hancom',
  휴켐스: 'Huchems Fine Chemical',
  NEW: 'Next Entertainment World',
  티엘비: 'TLB',
  네오팜: 'Neopharm',
  효성화학: 'Hyosung Chemical',
  PI첨단소재: 'PI Advanced Materials',
  HD현대미포: 'HD Hyundai Mipo',
  산일전기: 'Sanil Electric',
  현대그린푸드: 'Hyundai Greenfood',
  에이비엘바이오: 'ABL Bio',
  AP시스템: 'AP Systems',
  인터파크: 'Interpark',
  레이언스: 'Rayence',
  한진칼: 'Hanjin KAL',
  하이비젼시스템: 'Hi Vision System',
  코오롱글로벌: 'Kolon Global',
  인탑스: 'Intops',
  HSD엔진: 'HSD Engine',
  다나와: 'Danawa',
  인터로조: 'Interojo',
  동원산업: 'Dongwon Industries',
  동국제약: 'Dongkook Pharmaceutical',
  와이솔: 'Wisol',
  인크로스: 'Incross',
  SK케미칼: 'SK Chemicals',
  동화기업: 'Dongwha Enterprise',
  포스코대우: 'POSCO Daewoo',
  한화테크윈: 'Hanwha Techwin',
  파크시스템스: 'Park Systems',
  에코마케팅: 'Eco Marketing',
  콜마비앤에이치: 'Kolmar BNH',
  롯데정보통신: 'Lotte Data Communication',
  쌍용차: 'SsangYong Motor',
  현대코퍼레이션: 'Hyundai Corporation',
  하나머티리얼즈: 'Hana Materials',
  비나텍: 'Vinatech',
  교촌에프앤비: 'Kyochon F&B',
  코리아써키트: 'Korea Circuit',
  대한제강: 'Daehan Steel',
  테크윙: 'Techwing',
  세진중공업: 'Sejin Heavy Industries',
  다산네트웍스: 'DASAN Networks',
  LF: 'LF',
  비츠로셀: 'Vitzrocell',
  슈프리마: 'Suprema',
  코미코: 'Komico',
  골프존: 'Golfzon',
  이지바이오: 'EASY BIO',
  연우: 'Yonwoo',
  현대건설기계: 'Hyundai Construction Equipment',
  휠라코리아: 'FILA Korea',
  메리츠종금증권: 'Meritz Securities',
  다음카카오: 'Daum Kakao',
  LX하우시스: 'LX Hausys',
  실리콘투: 'Silicon2',
  SPC삼립: 'SPC Samlip',
  맥쿼리인프라: 'Macquarie Korea Infrastructure Fund',
  코오롱플라스틱: 'Kolon Plastics',
  두산엔진: 'Doosan Engine',
  대한해운: 'Korea Line',
  SK디앤디: 'SK D&D',
  금호산업: 'Kumho Industrial',
  포스코켐텍: 'POSCO Chemtech',
  KB손해보험: 'KB Insurance',
  금호석유화학: 'Kumho Petrochemical',
  더블유씨피: 'WCP',
  유니셈: 'Unisem',
  에스티아이: 'STI',
  나스미디어: 'Nasmedia',
  레고켐바이오: 'LigaChem Biosciences',
  풀무원: 'Pulmuone',
  슈피겐코리아: 'Spigen Korea',
  한국단자: 'Korea Electric Terminal',
  정상제이엘에스: 'Jungsang JLS',
  루트로닉: 'Lutronic',
  일진전기: 'Iljin Electric',
  에이블씨엔씨: 'ABLE C&C',
  헥토파이낸셜: 'Hecto Financial',
  메가스터디교육: 'Megastudy Edu',
  코윈테크: 'Kowin Tech',
  헥토이노베이션: 'Hecto Innovation',
  조이시티: 'Joycity',
  '무림P&P': 'Moorim P&P',
  현대일렉트릭: 'Hyundai Electric',
  넷마블게임즈: 'Netmarble Games',
  HD현대마린솔루션: 'HD Hyundai Marine Solution',
  달바글로벌: "d'Alba Global",
  미스토홀딩스: 'Misto Holdings',
  LG씨엔에스: 'LG CNS',
  한국토지신탁: 'Korea Asset In Trust',
  티앤엘: 'T&L',
  넥스틴: 'Nextin',
  LG하우시스: 'LG Hausys',
  평화정공: 'Pyeong Hwa Automotive',
  HS효성첨단소재: 'HS Hyosung Advanced Materials',
  오스코텍: 'Oscotec',
  성광벤드: 'Sungkwang Bend',
  AJ네트웍스: 'AJ Networks',
  한국전자금융: 'Korea Electronic Financial',
  LS전선아시아: 'LS Cable Asia',
  SKC코오롱PI: 'SKC Kolon PI',
  감성코퍼레이션: 'Gamsung Corporation',
  자이에스앤디: 'Xi S&D',
  'NHN KCP': 'NHN KCP',
  지니언스: 'Genians',
  루닛: 'Lunit',
  아이패밀리에스씨: 'iFamily SC',
  텔레칩스: 'Telechips',
  선데이토즈: 'Sundaytoz',
  칩스앤미디어: 'Chips&Media',

  /* ── 5차 보강 (2026-08-03) — 미커버 상위 150개에서 **확신하는 것만** ───────
     ⚠ 9개를 일부러 뺐다 — 우주일렉트로·트루엔·아이씨티케이·한중엔시에스·
        씨어스테크놀로지·사피엔반도체·안지오랩·제노코·파인엠텍·지어소프트.
        공식 영문 표기를 확인하지 못했다. **null 이 틀린 이름보다 낫다.**
     ⚠ 「NC」도 뺐다. 엔씨소프트로 보이지만 아카이브 표기만으로는 단정할 수 없다. */
  LS에코에너지: 'LS Eco Energy',
  명신산업: 'Myoungshin Industrial',
  토비스: 'Tovis',
  보령제약: 'Boryung Pharmaceutical',
  HPSP: 'HPSP',
  KG이니시스: 'KG Inicis',
  리가켐바이오: 'LigaChem Biosciences',
  나노신소재: 'Advanced Nano Products',
  인텍플러스: 'Intekplus',
  피엔티: 'PNT',
  대한약품: 'Daehan New Pharm',
  삼진제약: 'Samjin Pharmaceutical',
  휴맥스: 'Humax',
  CJ헬로비전: 'CJ HelloVision',
  한국카본: 'Hankuk Carbon',
  엘앤씨바이오: 'L&C Bio',
  유바이오로직스: 'EuBiologics',
  티에스이: 'TSE',
  지노믹트리: 'Genomictree',
  나이스정보통신: 'NICE Information & Telecommunication',
  원텍: 'Wontech',
  브이티: 'VT',
  휴비츠: 'Huvitz',
  금화피에스시: 'Kumhwa PSC',
  NICE평가정보: 'NICE Information Service',
  쿠쿠전자: 'Cuckoo Electronics',
  제넥신: 'Genexine',
  코스모신소재: 'Cosmo AM&T',
  코스맥스엔비티: 'COSMAX NBT',
  롯데이노베이트: 'Lotte Innovate',
  라온시큐어: 'Raonsecure',
  휴메딕스: 'Humedix',
  제이앤티씨: 'JNTC',
  SAMG엔터: 'SAMG Entertainment',
  대주전자재료: 'Daejoo Electronic Materials',
  일진하이솔루스: 'Iljin Hysolus',
  SK바이오사이언스: 'SK bioscience',
  비아트론: 'Viatron Technologies',
  삼영전자: 'Samyoung Electronics',
  현대상사: 'Hyundai Corporation',
  네오위즈게임즈: 'Neowiz Games',
  한진해운: 'Hanjin Shipping',
  대한전선: 'Taihan Cable & Solution',
  태웅: 'Taewoong',
  그린플러스: 'Green Plus',
  오로스테크놀로지: 'Oros Technology',
  대양전기공업: 'Daeyang Electric',
  락앤락: 'Lock&Lock',
  HD현대: 'HD Hyundai',
  성일하이텍: 'SungEel HiTech',
  동운아나텍: 'Dongwoon Anatech',
  'HL D&I': 'HL D&I Halla',
  쏘카: 'SOCAR',
  하이록코리아: 'Hy-Lok',
  글로벌텍스프리: 'Global Tax Free',
  LG헬로비전: 'LG HelloVision',
  현대리바트: 'Hyundai Livart',
  '디앤씨미디어': 'D&C Media',
  한진: 'Hanjin Transportation',
  DL: 'DL Holdings',
  미래에셋생명: 'Mirae Asset Life Insurance',
  JW중외제약: 'JW Pharmaceutical',
  코웰패션: 'Cowell Fashion',
  한신공영: 'Hanshin Engineering & Construction',
  '서부T&D': 'Seobu T&D',
  한미글로벌: 'Hanmi Global',
  올릭스: 'OliX Pharmaceuticals',
  하나기술: 'Hana Technology',
  오이솔루션: 'OE Solutions',
  레이: 'Ray',
  마이크로디지탈: 'Microdigital',
  바디텍메드: 'Boditech Med',
  NHN한국사이버결제: 'NHN KCP',
  현대하이스코: 'Hyundai Hysco',
  IPARK현대산업개발: 'HDC Hyundai Development',
  화신: 'Hwashin',
  선익시스템: 'Sunic System',
  TKG휴켐스: 'TKG Huchems',
  서흥: 'Suheung',
  삼화콘덴서: 'Samwha Capacitor',
  에이프릴바이오: 'April Biotherapeutics',
  로보티즈: 'Robotis',
  토니모리: 'Tonymoly',
  뷰노: 'VUNO',
  대우인터내셔널: 'Daewoo International',
  에치에프알: 'HFR',
  신성이엔지: 'Shinsung E&G',
  웹케시: 'Webcash',
  노바렉스: 'Novarex',
  씨에스베어링: 'CS Bearing',
  흥국에프엔비: 'Heungkuk F&B',
  디와이파워: 'DY Power',
  디엔에프: 'DNF',
  대우증권: 'Daewoo Securities',
  BS금융지주: 'BS Financial Group',
  다음: 'Daum Communications',
  덕산하이메탈: 'Duksan Hi-Metal',
  DN오토모티브: 'DN Automotive',
  한화엔진: 'Hanwha Engine',
  엑시콘: 'Exicon',
  쿠콘: 'Coocon',
  케이아이엔엑스: 'KINX',
  피에이치에이: 'PHA',
  쇼박스: 'Showbox',
  한국자산신탁: 'Korea Asset Trust',
  상아프론테크: 'Sang-A Frontec',
  제닉: 'Genic',
  삼천리: 'Samchully',
  엠플러스: 'M Plus',
  두산테스나: 'Doosan Tesna',
  SK이터닉스: 'SK Eternix',
  쎄트렉아이: 'Satrec Initiative',
  '진성티이씨': 'Jinsung T.E.C',
  송원산업: 'Songwon Industrial',
  비올: 'Viol',
  환인제약: 'Whanin Pharmaceutical',
  제이시스메디칼: 'Jeisys Medical',
  파워로직스: 'Powerlogics',
  에스텍: 'S-Tech',
  한진중공업: 'Hanjin Heavy Industries & Construction',
  LIG손해보험: 'LIG Insurance',
  제이에스코퍼레이션: 'JS Corporation',
  HL홀딩스: 'HL Holdings',
  자화전자: 'Jahwa Electronics',
  레이크머티리얼즈: 'Lake Materials',
  빅솔론: 'BIXOLON',
  퓨쳐켐: 'FutureChem',
  펩트론: 'Peptron',
  넥슨게임즈: 'NEXON Games',
  이크레더블: 'eCredible',
  엘비세미콘: 'LB Semicon',
  이수화학: 'Isu Chemical',
  한라: 'Halla',
  뉴트리바이오텍: 'Nutribiotech',
  한국타이어월드와이드: 'Hankook Tire Worldwide',
  애경유화: 'AEKYUNG Petrochemical',
  LG생명과학: 'LG Life Sciences',
  유니테스트: 'Unitest',
  GST: 'GST',
};

/**
 * 한글 종목명을 영문으로 편다.
 * **사전에 없으면 null 이다 — 추측하지 않는다.**
 */
export function describeSubject(ko) {
  if (!ko) return null;
  return SUBJECTS[ko] ?? null;
}

/** 사전 통계. `/v1/meta` 가 쓴다. */
export const SUBJECT_STATS = {
  entries: Object.keys(SUBJECTS).length,
  /** 실측 커버리지. 아카이브 66,071건 중 영문이 나가는 비율(2026-08-03 KST 측정). */
  coveragePct: 86.1,
  note: 'Curated by report frequency. Names not yet in the dictionary return null rather than a guess.',
};
