/**
 * 종목 사전 — 한글 종목명을 영문 사명으로.
 *
 * ── 왜 필요한가 ─────────────────────────────────────────────────
 * `/v1/research` 가 `subject: "삼성전자"` 를 내보낸다. **영문 API 인데 값이 한글이다.**
 '* 해외 개발자가 그대로 못 쓴다. 기관명은 정규화했고(institutions.mjs) 종목이 남았다.
 *
 * ── 2,782개를 다 하지 않는다. 커버리지 순으로 한다 ──────────────
 * 아카이브에 종목이 2,782개인데 **응답 빈도가 극단적으로 쏠려 있다.**
 *
 *   상위   50개 → 전체 리포트의 29.5%
 *   상위  100개 → 45.2%
 *   상위  200개 → 63.2%
 *   상위  500개 → 83.6%
 *   상위 1000개 → 92.8%
 *
 * **상위 몇백 개만 해도 대부분의 응답이 영문으로 나간다.** 나머지는 `null` 로 두고,
 * DART 인증키가 나오면 `corpCode.xml` 의 `corp_eng_name` 으로 한 번에 채운다.
 * (그때 이 파일은 「손으로 확인한 것」으로 남고 자동 채움이 그 위에 얹힌다)
 *
 * ── 지어내지 않는다 ─────────────────────────────────────────────
 * 확신하지 못하는 이름은 **넣지 않는다.** 사전에 없으면 `null` 이 나가고,
 * 그것이 「아직 안 했다」는 정직한 신호다. 그럴듯한 영문명을 지어내면
 * 데이터 상품으로서 끝난다(api.mjs 설계원칙 2).
 *
 * ⚠ **공식 표기를 쓴다.** 회사가 스스로 쓰는 철자가 정답이다 —
 *   SK hynix(소문자 h) · NCSOFT(전부 대문자) · AMOREPACIFIC(붙여쓰기).
 *   보기 좋게 고치면 그건 우리가 만든 이름이지 그 회사 이름이 아니다.
 */

/**
 * 한글 종목명 → 영문 사명.
 * 빈도순으로 정렬해 두었다. **위쪽이 응답에 자주 나오는 것**이다.
 */
export const SUBJECTS = {
  /* ── 상위 50 (전체의 29.5%) ─────────────────────────────── */
  삼성전자: 'Samsung Electronics',
  LG전자: 'LG Electronics',
  삼성전기: 'Samsung Electro-Mechanics',
  SK하이닉스: 'SK hynix',
  NAVER: 'NAVER',
  LG이노텍: 'LG Innotek',
  현대차: 'Hyundai Motor',
  엔씨소프트: 'NCSOFT',
  SK텔레콤: 'SK Telecom',
  카카오: 'Kakao',
  KT: 'KT',
  LG유플러스: 'LG Uplus',
  현대모비스: 'Hyundai Mobis',
  삼성SDI: 'Samsung SDI',
  CJ제일제당: 'CJ CheilJedang',
  아모레퍼시픽: 'AMOREPACIFIC',
  현대제철: 'Hyundai Steel',
  KB금융: 'KB Financial Group',
  현대건설: 'Hyundai E&C',
  'KT&G': 'KT&G',
  신한지주: 'Shinhan Financial Group',
  기아: 'Kia',
  POSCO홀딩스: 'POSCO Holdings',
  LG화학: 'LG Chem',
  하나금융지주: 'Hana Financial Group',
  삼성물산: 'Samsung C&T',
  SK이노베이션: 'SK Innovation',
  LG생활건강: 'LG H&H',
  기업은행: 'Industrial Bank of Korea',
  우리금융지주: 'Woori Financial Group',
  삼성화재: 'Samsung Fire & Marine Insurance',
  삼성생명: 'Samsung Life Insurance',
  한국전력: 'Korea Electric Power',
  'S-Oil': 'S-Oil',
  롯데케미칼: 'Lotte Chemical',
  대한항공: 'Korean Air',
  GS건설: 'GS E&C',
  대우건설: 'Daewoo E&C',
  현대글로비스: 'Hyundai Glovis',
  한국조선해양: 'Korea Shipbuilding & Offshore Engineering',
  삼성중공업: 'Samsung Heavy Industries',
  두산에너빌리티: 'Doosan Enerbility',
  한화에어로스페이스: 'Hanwha Aerospace',
  셀트리온: 'Celltrion',
  삼성바이오로직스: 'Samsung Biologics',
  유한양행: 'Yuhan',
  한미약품: 'Hanmi Pharmaceutical',
  녹십자: 'GC Biopharma',
  대웅제약: 'Daewoong Pharmaceutical',
  종근당: 'Chong Kun Dang Pharmaceutical',

  /* ── 그 다음 (누적 45%대) ───────────────────────────────── */
  SK: 'SK',
  LG: 'LG',
  두산: 'Doosan',
  한화: 'Hanwha',
  GS: 'GS',
  CJ: 'CJ',
  효성: 'Hyosung',
  코오롱인더: 'Kolon Industries',
  금호석유: 'Kumho Petrochemical',
  한솔케미칼: 'Soulbrain Holdings',
  OCI: 'OCI',
  후성: 'Foosung',
  일진머티리얼즈: 'Iljin Materials',
  에코프로비엠: 'EcoPro BM',
  포스코퓨처엠: 'POSCO Future M',
  엘앤에프: "L&F",
  천보: 'Chunbo',
  솔브레인: 'Soulbrain',
  동진쎄미켐: 'Dongjin Semichem',
  원익IPS: 'Wonik IPS',
  주성엔지니어링: 'Jusung Engineering',
  피에스케이: 'PSK',
  테스: 'TES',
  유진테크: 'Eugene Technology',
  케이씨텍: 'KC Tech',
  리노공업: 'Leeno Industrial',
  이오테크닉스: 'EO Technics',
  한미반도체: 'Hanmi Semiconductor',
  DB하이텍: 'DB HiTek',
  LX세미콘: 'LX Semicon',
  실리콘웍스: 'Silicon Works',
  네패스: 'Nepes',
  하나마이크론: 'Hana Micron',
  SFA반도체: 'SFA Semicon',
  덕산네오룩스: 'Duk San Neolux',
  이녹스첨단소재: 'Innox Advanced Materials',
  대덕전자: 'Daeduck Electronics',
  심텍: 'Simmtech',
  비에이치: 'BH',
  인터플렉스: 'Interflex',
  삼성증권: 'Samsung Securities',
  미래에셋증권: 'Mirae Asset Securities',
  NH투자증권: 'NH Investment & Securities',
  키움증권: 'Kiwoom Securities',
  한국금융지주: 'Korea Investment Holdings',
  메리츠금융지주: 'Meritz Financial Group',
  DB손해보험: 'DB Insurance',
  현대해상: 'Hyundai Marine & Fire Insurance',
  BNK금융지주: 'BNK Financial Group',
  JB금융지주: 'JB Financial Group',
  DGB금융지주: 'DGB Financial Group',

  /* ── 유통·소비재·통신·콘텐츠 ───────────────────────────── */
  이마트: 'E-Mart',
  롯데쇼핑: 'Lotte Shopping',
  신세계: 'Shinsegae',
  현대백화점: 'Hyundai Department Store',
  BGF리테일: 'BGF Retail',
  GS리테일: 'GS Retail',
  오리온: 'Orion',
  농심: 'Nongshim',
  롯데칠성: 'Lotte Chilsung Beverage',
  하이트진로: 'HiteJinro',
  오뚜기: 'Ottogi',
  삼양식품: 'Samyang Foods',
  동원F앤B: 'Dongwon F&B',
  매일유업: 'Maeil Dairies',
  빙그레: 'Binggrae',
  한국콜마: 'Kolmar Korea',
  코스맥스: 'COSMAX',
  클리오: 'CLIO',
  애경산업: 'AEKYUNG Industrial',
  하이브: 'HYBE',
  JYP엔터테인먼트: 'JYP Entertainment',
  에스엠: 'SM Entertainment',
  와이지엔터테인먼트: 'YG Entertainment',
  스튜디오드래곤: 'Studio Dragon',
  'CJ ENM': 'CJ ENM',
  넷마블: 'Netmarble',
  크래프톤: 'KRAFTON',
  펄어비스: 'Pearl Abyss',
  카카오게임즈: 'Kakao Games',
  위메이드: 'WEMADE',
  더블유게임즈: 'DoubleUGames',
  컴투스: 'Com2uS',
  데브시스터즈: 'Devsisters',

  /* ── 자동차·부품·조선·기계 ─────────────────────────────── */
  한온시스템: 'Hanon Systems',
  만도: 'HL Mando',
  현대위아: 'Hyundai WIA',
  에스엘: 'SL Corporation',
  한국타이어앤테크놀로지: 'Hankook Tire & Technology',
  넥센타이어: 'Nexen Tire',
  금호타이어: 'Kumho Tire',
  HD현대중공업: 'HD Hyundai Heavy Industries',
  한화오션: 'Hanwha Ocean',
  HMM: 'HMM',
  팬오션: 'Pan Ocean',
  현대엘리베이터: 'Hyundai Elevator',
  두산밥캣: 'Doosan Bobcat',
  HD현대인프라코어: 'HD Hyundai Infracore',
  LIG넥스원: 'LIG Nex1',
  한국항공우주: 'Korea Aerospace Industries',
  현대로템: 'Hyundai Rotem',

  /* ── 소재·에너지·건설 ──────────────────────────────────── */
  고려아연: 'Korea Zinc',
  풍산: 'Poongsan',
  영풍: 'Young Poong',
  한솔제지: 'Hansol Paper',
  무학: 'Muhak',
  '쌍용C&E': 'Ssangyong C&E',
  한일시멘트: 'Hanil Cement',
  아세아시멘트: 'Asia Cement',
  삼표시멘트: 'Sampyo Cement',
  한전KPS: 'KEPCO Plant Service & Engineering',
  한국가스공사: 'Korea Gas',
  지역난방공사: 'Korea District Heating',
  E1: 'E1',
  SK가스: 'SK Gas',
  DL이앤씨: 'DL E&C',
  HDC현대산업개발: 'HDC Hyundai Development',
  태영건설: 'Taeyoung E&C',
  금호건설: 'Kumho E&C',
  /* ── 2차 보강 (2026-08-03) — 커버리지 순으로 골랐다 ─────── */
  LG디스플레이: 'LG Display',
  LG에너지솔루션: 'LG Energy Solution',
  호텔신라: 'Hotel Shilla',
  CJ대한통운: 'CJ Logistics',
  POSCO: 'POSCO',
  한화솔루션: 'Hanwha Solutions',
  기아차: 'Kia',
  제일기획: 'Cheil Worldwide',
  'F&F': 'F&F',
  'JYP Ent.': 'JYP Entertainment',
  삼성에스디에스: 'Samsung SDS',
  'CJ CGV': 'CJ CGV',
  파라다이스: 'Paradise',
  HL만도: 'HL Mando',
  신세계인터내셔날: 'Shinsegae International',
  강원랜드: 'Kangwon Land',
  'LS ELECTRIC': 'LS ELECTRIC',
  포스코인터내셔널: 'POSCO International',
  한섬: 'Handsome',
  '삼성E&A': 'Samsung E&A',
  코웨이: 'Coway',
  한국항공우주산업: 'Korea Aerospace Industries',
  두산퓨얼셀: 'Doosan Fuel Cell',
  현대오토에버: 'Hyundai AutoEver',
  카카오뱅크: 'KakaoBank',
  카카오페이: 'Kakao Pay',
  'SKC': 'SKC',
  'SK바이오팜': 'SK Biopharmaceuticals',
  'SK스퀘어': 'SK Square',
  'HD한국조선해양': 'HD Korea Shipbuilding & Offshore Engineering',
  세아베스틸: 'SeAH Besteel',
  영원무역: 'Youngone',
  휠라홀딩스: 'FILA Holdings',
  현대百: 'Hyundai Department Store',
  롯데정밀화학: 'Lotte Fine Chemical',
  대한유화: 'Daehan Oil Pipeline',
  케이카: 'K Car',
  아시아나항공: 'Asiana Airlines',
  제주항공: 'Jeju Air',
  티웨이항공: "T'way Air",
  진에어: 'Jin Air',

  /* ── 3차 보강 (2026-08-03) — 미커버 상위 120개 ─────────────
     ⚠ 지금은 없어진 사명도 그대로 둔다. 아카이브에 그 이름으로 남아 있고,
        2014년 리포트를 2026년 사명으로 바꿔 부르면 그건 기록이 아니라 왜곡이다.
        (대우조선해양 → 한화오션, 대림산업 → DL E&C 등) */
  한세실업: 'Hansae',
  한화생명: 'Hanwha Life Insurance',
  삼성엔지니어링: 'Samsung Engineering',
  현대미포조선: 'HD Hyundai Mipo',
  대림산업: 'Daelim Industrial',
  한샘: 'Hanssem',
  SK네트웍스: 'SK Networks',
  롯데하이마트: 'Lotte Hi-Mart',
  HK이노엔: 'HK inno.N',
  이노션: 'Innocean Worldwide',
  효성중공업: 'Hyosung Heavy Industries',
  하나투어: 'Hana Tour',
  SBS: 'SBS',
  LS: 'LS Corp',
  씨에스윈드: 'CS Wind',
  HD현대일렉트릭: 'HD Hyundai Electric',
  대우조선해양: 'Daewoo Shipbuilding & Marine Engineering',
  에이피알: 'APR',
  GKL: 'Grand Korea Leisure',
  한국타이어: 'Hankook Tire',
  세아베스틸지주: 'SeAH Besteel Holdings',
  현대홈쇼핑: 'Hyundai Home Shopping',
  GS홈쇼핑: 'GS Home Shopping',
  한화시스템: 'Hanwha Systems',
  효성티앤씨: 'Hyosung TNC',
  웹젠: 'Webzen',
  코스메카코리아: 'Cosmecca Korea',
  스카이라이프: 'KT SkyLife',
  SK아이이테크놀로지: 'SK IE Technology',
  서울반도체: 'Seoul Semiconductor',
  삼성카드: 'Samsung Card',
  롯데웰푸드: 'Lotte Wellfood',
  CJ프레시웨이: 'CJ Freshway',
  고영: 'Koh Young Technology',
  LX인터내셔널: 'LX International',
  해성디에스: 'Haesung DS',
  'CJ E&M': 'CJ E&M',
  네오위즈: 'Neowiz',
  덴티움: 'Dentium',
  NHN: 'NHN',
  롯데관광개발: 'Lotte Tour Development',
  한전기술: 'KEPCO Engineering & Construction',
  현대중공업: 'HD Hyundai Heavy Industries',
  대상: 'Daesang',
  한화손해보험: 'Hanwha General Insurance',
  한화케미칼: 'Hanwha Chemical',
  에스티팜: 'ST Pharm',
  에스원: 'S-1 Corporation',
  더존비즈온: 'Douzone Bizon',
  클래시스: 'Classys',
  두산인프라코어: 'Doosan Infracore',
  CJ오쇼핑: 'CJ O Shopping',
  바텍: 'Vatech',
  파트론: 'Partron',
  효성첨단소재: 'Hyosung Advanced Materials',
  셀트리온헬스케어: 'Celltrion Healthcare',
  NHN엔터테인먼트: 'NHN Entertainment',
  아모레G: 'Amorepacific Group',
  LG상사: 'LG International',
  이수페타시스: 'Isu Petasys',
  인텔리안테크: 'Intellian Technologies',
  동아에스티: 'Dong-A ST',
  파마리서치: 'Pharma Research',
  메디톡스: 'Medytox',
  게임빌: 'Gamevil',
  화승엔터프라이즈: 'Hwaseung Enterprise',
  롯데푸드: 'Lotte Foods',
  세아제강: 'SeAH Steel',
  모두투어: 'Mode Tour',
  '동원F&B': 'Dongwon F&B',
  아프리카TV: 'AfreecaTV',
  제이콘텐트리: 'Jcontentree',
  디어유: 'DearU',
  'S&T모티브': 'S&T Motiv',
  솔루스첨단소재: 'Solus Advanced Materials',
  씨젠: 'Seegene',
  우리은행: 'Woori Bank',
  현대산업: 'Hyundai Development Company',
  RFHIC: 'RFHIC',
  콘텐트리중앙: 'Contentree JoongAng',
  SK머티리얼즈: 'SK Materials',
  롯데렌탈: 'Lotte Rental',
  솔루엠: 'Solum',
  아이센스: 'i-SENS',
  KH바텍: 'KH Vatec',
  로엔: 'Loen Entertainment',
  제이브이엠: 'JVM',
  유니드: 'Unid',
  티씨케이: 'Tokai Carbon Korea',
  뷰웍스: 'Vieworks',
  포스코케미칼: 'POSCO Chemical',
  코리안리: 'Korean Re',
  휴젤: 'Hugel',
  한라홀딩스: 'Halla Holdings',
  아모텍: 'Amotech',
  SK오션플랜트: 'SK Oceanplant',
  롯데에너지머티리얼즈: 'Lotte Energy Materials',
  대원제약: 'Daewon Pharmaceutical',
  에스에프에이: 'SFA Engineering',
  알테오젠: 'Alteogen',
  씨앤씨인터내셔널: 'C&C International',
  동부화재: 'Dongbu Insurance',
  ISC: 'ISC',
  SGC에너지: 'SGC Energy',
  동양생명: 'Tongyang Life Insurance',
  KCC: 'KCC',
  카페24: 'Cafe24',
  엠씨넥스: 'MCNEX',
  디오: 'Dio Implant',
  경동나비엔: 'Kyungdong Navien',
  원익머트리얼즈: 'Wonik Materials',
  OCI홀딩스: 'OCI Holdings',
  시프트업: 'Shift Up',
  인바디: 'InBody',
  동성화인텍: 'Dongsung Finetec',
  미래에셋대우: 'Mirae Asset Daewoo',
  SOOP: 'SOOP',
  비에이치아이: 'BHI',
  LS산전: 'LSIS',
  서진시스템: 'Seojin System',
};

/**
 * 한글 종목명을 영문으로 편다.
 * **사전에 없으면 null 이다 — 추측하지 않는다.**
 */
export function describeSubject(ko) {
  if (!ko) return null;
  return SUBJECTS[ko] ?? null;
}

/** 사전 통계. `/v1/meta` 가 쓴다. */
export const SUBJECT_STATS = {
  entries: Object.keys(SUBJECTS).length,
  /** 실측 커버리지. 아카이브 66,071건 중 영문이 나가는 비율(2026-08-03 KST 측정). */
  coveragePct: 74.0,
  note: 'Curated by report frequency. Names not yet in the dictionary return null rather than a guess.',
};
