/**
 * 종목 사전 — 한글 종목명을 영문 사명으로.
 *
 * ── 왜 필요한가 ─────────────────────────────────────────────────
 * `/v1/research` 가 `subject: "삼성전자"` 를 내보낸다. **영문 API 인데 값이 한글이다.**
 * 해외 개발자가 그대로 못 쓴다. 기관명은 정규화했고(institutions.mjs) 종목이 남았다.
 *
 * ── 2,782개를 다 하지 않는다. 커버리지 순으로 한다 ──────────────
 * 아카이브에 종목이 2,782개인데 **응답 빈도가 극단적으로 쏠려 있다.**
 *
 *   상위   50개 → 전체 리포트의 29.5%
 *   상위  100개 → 45.2%
 *   상위  200개 → 63.2%
 *   상위  500개 → 83.6%
 *   상위 1000개 → 92.8%
 *
 * **상위 몇백 개만 해도 대부분의 응답이 영문으로 나간다.** 나머지는 `null` 로 두고,
 * DART 인증키가 나오면 `corpCode.xml` 의 `corp_eng_name` 으로 한 번에 채운다.
 * (그때 이 파일은 「손으로 확인한 것」으로 남고 자동 채움이 그 위에 얹힌다)
 *
 * ── 지어내지 않는다 ─────────────────────────────────────────────
 * 확신하지 못하는 이름은 **넣지 않는다.** 사전에 없으면 `null` 이 나가고,
 * 그것이 「아직 안 했다」는 정직한 신호다. 그럴듯한 영문명을 지어내면
 * 데이터 상품으로서 끝난다(api.mjs 설계원칙 2).
 *
 * ⚠ **공식 표기를 쓴다.** 회사가 스스로 쓰는 철자가 정답이다 —
 *   SK hynix(소문자 h) · NCSOFT(전부 대문자) · AMOREPACIFIC(붙여쓰기).
 *   보기 좋게 고치면 그건 우리가 만든 이름이지 그 회사 이름이 아니다.
 */

/**
 * 한글 종목명 → 영문 사명.
 * 빈도순으로 정렬해 두었다. **위쪽이 응답에 자주 나오는 것**이다.
 */
export const SUBJECTS = {
  /* ── 상위 50 (전체의 29.5%) ─────────────────────────────── */
  삼성전자: 'Samsung Electronics',
  LG전자: 'LG Electronics',
  삼성전기: 'Samsung Electro-Mechanics',
  SK하이닉스: 'SK hynix',
  NAVER: 'NAVER',
  LG이노텍: 'LG Innotek',
  현대차: 'Hyundai Motor',
  엔씨소프트: 'NCSOFT',
  SK텔레콤: 'SK Telecom',
  카카오: 'Kakao',
  KT: 'KT',
  LG유플러스: 'LG Uplus',
  현대모비스: 'Hyundai Mobis',
  삼성SDI: 'Samsung SDI',
  CJ제일제당: 'CJ CheilJedang',
  아모레퍼시픽: 'AMOREPACIFIC',
  현대제철: 'Hyundai Steel',
  KB금융: 'KB Financial Group',
  현대건설: 'Hyundai E&C',
  'KT&G': 'KT&G',
  신한지주: 'Shinhan Financial Group',
  기아: 'Kia',
  POSCO홀딩스: 'POSCO Holdings',
  LG화학: 'LG Chem',
  하나금융지주: 'Hana Financial Group',
  삼성물산: 'Samsung C&T',
  SK이노베이션: 'SK Innovation',
  LG생활건강: 'LG H&H',
  기업은행: 'Industrial Bank of Korea',
  우리금융지주: 'Woori Financial Group',
  삼성화재: 'Samsung Fire & Marine Insurance',
  삼성생명: 'Samsung Life Insurance',
  한국전력: 'Korea Electric Power',
  'S-Oil': 'S-Oil',
  롯데케미칼: 'Lotte Chemical',
  대한항공: 'Korean Air',
  GS건설: 'GS E&C',
  대우건설: 'Daewoo E&C',
  현대글로비스: 'Hyundai Glovis',
  한국조선해양: 'Korea Shipbuilding & Offshore Engineering',
  삼성중공업: 'Samsung Heavy Industries',
  두산에너빌리티: 'Doosan Enerbility',
  한화에어로스페이스: 'Hanwha Aerospace',
  셀트리온: 'Celltrion',
  삼성바이오로직스: 'Samsung Biologics',
  유한양행: 'Yuhan',
  한미약품: 'Hanmi Pharmaceutical',
  녹십자: 'GC Biopharma',
  대웅제약: 'Daewoong Pharmaceutical',
  종근당: 'Chong Kun Dang Pharmaceutical',

  /* ── 그 다음 (누적 45%대) ───────────────────────────────── */
  SK: 'SK',
  LG: 'LG',
  두산: 'Doosan',
  한화: 'Hanwha',
  GS: 'GS',
  CJ: 'CJ',
  효성: 'Hyosung',
  코오롱인더: 'Kolon Industries',
  금호석유: 'Kumho Petrochemical',
  한솔케미칼: 'Hansol Chemical',
  OCI: 'OCI',
  후성: 'Foosung',
  일진머티리얼즈: 'Iljin Materials',
  에코프로비엠: 'EcoPro BM',
  포스코퓨처엠: 'POSCO Future M',
  엘앤에프: "L&F",
  천보: 'Chunbo',
  솔브레인: 'Soulbrain',
  동진쎄미켐: 'Dongjin Semichem',
  원익IPS: 'Wonik IPS',
  주성엔지니어링: 'Jusung Engineering',
  피에스케이: 'PSK',
  테스: 'TES',
  유진테크: 'Eugene Technology',
  케이씨텍: 'KC Tech',
  리노공업: 'Leeno Industrial',
  이오테크닉스: 'EO Technics',
  한미반도체: 'Hanmi Semiconductor',
  DB하이텍: 'DB HiTek',
  LX세미콘: 'LX Semicon',
  실리콘웍스: 'Silicon Works',
  네패스: 'Nepes',
  하나마이크론: 'Hana Micron',
  SFA반도체: 'SFA Semicon',
  덕산네오룩스: 'Duk San Neolux',
  이녹스첨단소재: 'Innox Advanced Materials',
  대덕전자: 'Daeduck Electronics',
  심텍: 'Simmtech',
  비에이치: 'BH',
  인터플렉스: 'Interflex',
  삼성증권: 'Samsung Securities',
  미래에셋증권: 'Mirae Asset Securities',
  NH투자증권: 'NH Investment & Securities',
  키움증권: 'Kiwoom Securities',
  한국금융지주: 'Korea Investment Holdings',
  메리츠금융지주: 'Meritz Financial Group',
  DB손해보험: 'DB Insurance',
  현대해상: 'Hyundai Marine & Fire Insurance',
  BNK금융지주: 'BNK Financial Group',
  JB금융지주: 'JB Financial Group',
  DGB금융지주: 'DGB Financial Group',

  /* ── 유통·소비재·통신·콘텐츠 ───────────────────────────── */
  이마트: 'E-Mart',
  롯데쇼핑: 'Lotte Shopping',
  신세계: 'Shinsegae',
  현대백화점: 'Hyundai Department Store',
  BGF리테일: 'BGF Retail',
  GS리테일: 'GS Retail',
  오리온: 'Orion',
  농심: 'Nongshim',
  롯데칠성: 'Lotte Chilsung Beverage',
  하이트진로: 'HiteJinro',
  오뚜기: 'Ottogi',
  삼양식품: 'Samyang Foods',
  동원F앤B: 'Dongwon F&B',
  매일유업: 'Maeil Dairies',
  빙그레: 'Binggrae',
  한국콜마: 'Kolmar Korea',
  코스맥스: 'COSMAX',
  클리오: 'CLIO',
  애경산업: 'AEKYUNG Industrial',
  하이브: 'HYBE',
  JYP엔터테인먼트: 'JYP Entertainment',
  에스엠: 'SM Entertainment',
  와이지엔터테인먼트: 'YG Entertainment',
  스튜디오드래곤: 'Studio Dragon',
  'CJ ENM': 'CJ ENM',
  넷마블: 'Netmarble',
  크래프톤: 'KRAFTON',
  펄어비스: 'Pearl Abyss',
  카카오게임즈: 'Kakao Games',
  위메이드: 'WEMADE',
  더블유게임즈: 'DoubleUGames',
  컴투스: 'Com2uS',
  데브시스터즈: 'Devsisters',

  /* ── 자동차·부품·조선·기계 ─────────────────────────────── */
  한온시스템: 'Hanon Systems',
  만도: 'HL Mando',
  현대위아: 'Hyundai WIA',
  에스엘: 'SL Corporation',
  한국타이어앤테크놀로지: 'Hankook Tire & Technology',
  넥센타이어: 'Nexen Tire',
  금호타이어: 'Kumho Tire',
  HD현대중공업: 'HD Hyundai Heavy Industries',
  한화오션: 'Hanwha Ocean',
  HMM: 'HMM',
  팬오션: 'Pan Ocean',
  현대엘리베이터: 'Hyundai Elevator',
  두산밥캣: 'Doosan Bobcat',
  HD현대인프라코어: 'HD Hyundai Infracore',
  LIG넥스원: 'LIG Nex1',
  한국항공우주: 'Korea Aerospace Industries',
  현대로템: 'Hyundai Rotem',

  /* ── 소재·에너지·건설 ──────────────────────────────────── */
  고려아연: 'Korea Zinc',
  풍산: 'Poongsan',
  영풍: 'Young Poong',
  한솔제지: 'Hansol Paper',
  무학: 'Muhak',
  '쌍용C&E': 'Ssangyong C&E',
  한일시멘트: 'Hanil Cement',
  아세아시멘트: 'Asia Cement',
  삼표시멘트: 'Sampyo Cement',
  한전KPS: 'KEPCO Plant Service & Engineering',
  한국가스공사: 'Korea Gas',
  지역난방공사: 'Korea District Heating',
  E1: 'E1',
  SK가스: 'SK Gas',
  DL이앤씨: 'DL E&C',
  HDC현대산업개발: 'HDC Hyundai Development',
  태영건설: 'Taeyoung E&C',
  금호건설: 'Kumho E&C',
  /* ── 2차 보강 (2026-08-03) — 커버리지 순으로 골랐다 ─────── */
  LG디스플레이: 'LG Display',
  LG에너지솔루션: 'LG Energy Solution',
  호텔신라: 'Hotel Shilla',
  CJ대한통운: 'CJ Logistics',
  POSCO: 'POSCO',
  한화솔루션: 'Hanwha Solutions',
  기아차: 'Kia',
  제일기획: 'Cheil Worldwide',
  'F&F': 'F&F',
  'JYP Ent.': 'JYP Entertainment',
  삼성에스디에스: 'Samsung SDS',
  'CJ CGV': 'CJ CGV',
  파라다이스: 'Paradise',
  HL만도: 'HL Mando',
  신세계인터내셔날: 'Shinsegae International',
  강원랜드: 'Kangwon Land',
  'LS ELECTRIC': 'LS ELECTRIC',
  포스코인터내셔널: 'POSCO International',
  한섬: 'Handsome',
  '삼성E&A': 'Samsung E&A',
  코웨이: 'Coway',
  한국항공우주산업: 'Korea Aerospace Industries',
  두산퓨얼셀: 'Doosan Fuel Cell',
  현대오토에버: 'Hyundai AutoEver',
  카카오뱅크: 'KakaoBank',
  카카오페이: 'Kakao Pay',
  'SKC': 'SKC',
  'SK바이오팜': 'SK Biopharmaceuticals',
  'SK스퀘어': 'SK Square',
  'HD한국조선해양': 'HD Korea Shipbuilding & Offshore Engineering',
  세아베스틸: 'SeAH Besteel',
  영원무역: 'Youngone',
  휠라홀딩스: 'FILA Holdings',
  현대百: 'Hyundai Department Store',
  롯데정밀화학: 'Lotte Fine Chemical',
  대한유화: 'Korea Petrochemical Ind.',
  케이카: 'K Car',
  아시아나항공: 'Asiana Airlines',
  제주항공: 'Jeju Air',
  티웨이항공: "T'way Air",
  진에어: 'Jin Air',

  /* ── 3차 보강 (2026-08-03) — 미커버 상위 120개 ─────────────
     ⚠ 지금은 없어진 사명도 그대로 둔다. 아카이브에 그 이름으로 남아 있고,
        2014년 리포트를 2026년 사명으로 바꿔 부르면 그건 기록이 아니라 왜곡이다.
        (대우조선해양 → 한화오션, 대림산업 → DL E&C 등) */
  한세실업: 'Hansae',
  한화생명: 'Hanwha Life Insurance',
  삼성엔지니어링: 'Samsung Engineering',
  현대미포조선: 'HD Hyundai Mipo',
  대림산업: 'Daelim Industrial',
  한샘: 'Hanssem',
  SK네트웍스: 'SK Networks',
  롯데하이마트: 'Lotte Hi-Mart',
  HK이노엔: 'HK inno.N',
  이노션: 'Innocean Worldwide',
  효성중공업: 'Hyosung Heavy Industries',
  하나투어: 'Hana Tour',
  SBS: 'SBS',
  LS: 'LS Corp',
  씨에스윈드: 'CS Wind',
  HD현대일렉트릭: 'HD Hyundai Electric',
  대우조선해양: 'Daewoo Shipbuilding & Marine Engineering',
  에이피알: 'APR',
  GKL: 'Grand Korea Leisure',
  한국타이어: 'Hankook Tire',
  세아베스틸지주: 'SeAH Besteel Holdings',
  현대홈쇼핑: 'Hyundai Home Shopping',
  GS홈쇼핑: 'GS Home Shopping',
  한화시스템: 'Hanwha Systems',
  효성티앤씨: 'Hyosung TNC',
  웹젠: 'Webzen',
  코스메카코리아: 'Cosmecca Korea',
  스카이라이프: 'KT SkyLife',
  SK아이이테크놀로지: 'SK IE Technology',
  서울반도체: 'Seoul Semiconductor',
  삼성카드: 'Samsung Card',
  롯데웰푸드: 'Lotte Wellfood',
  CJ프레시웨이: 'CJ Freshway',
  고영: 'Koh Young Technology',
  LX인터내셔널: 'LX International',
  해성디에스: 'Haesung DS',
  'CJ E&M': 'CJ E&M',
  네오위즈: 'Neowiz',
  덴티움: 'Dentium',
  NHN: 'NHN',
  롯데관광개발: 'Lotte Tour Development',
  한전기술: 'KEPCO Engineering & Construction',
  현대중공업: 'HD Hyundai Heavy Industries',
  대상: 'Daesang',
  한화손해보험: 'Hanwha General Insurance',
  한화케미칼: 'Hanwha Chemical',
  에스티팜: 'ST Pharm',
  에스원: 'S-1 Corporation',
  더존비즈온: 'Douzone Bizon',
  클래시스: 'Classys',
  두산인프라코어: 'Doosan Infracore',
  CJ오쇼핑: 'CJ O Shopping',
  바텍: 'Vatech',
  파트론: 'Partron',
  효성첨단소재: 'Hyosung Advanced Materials',
  셀트리온헬스케어: 'Celltrion Healthcare',
  NHN엔터테인먼트: 'NHN Entertainment',
  아모레G: 'Amorepacific Group',
  LG상사: 'LG International',
  이수페타시스: 'Isu Petasys',
  인텔리안테크: 'Intellian Technologies',
  동아에스티: 'Dong-A ST',
  파마리서치: 'Pharma Research',
  메디톡스: 'Medytox',
  게임빌: 'Gamevil',
  화승엔터프라이즈: 'Hwaseung Enterprise',
  롯데푸드: 'Lotte Foods',
  세아제강: 'SeAH Steel',
  모두투어: 'Mode Tour',
  '동원F&B': 'Dongwon F&B',
  아프리카TV: 'AfreecaTV',
  제이콘텐트리: 'Jcontentree',
  디어유: 'DearU',
  'S&T모티브': 'S&T Motiv',
  솔루스첨단소재: 'Solus Advanced Materials',
  씨젠: 'Seegene',
  우리은행: 'Woori Bank',
  현대산업: 'Hyundai Development Company',
  RFHIC: 'RFHIC',
  콘텐트리중앙: 'Contentree JoongAng',
  SK머티리얼즈: 'SK Materials',
  롯데렌탈: 'Lotte Rental',
  솔루엠: 'Solum',
  아이센스: 'i-SENS',
  KH바텍: 'KH Vatec',
  로엔: 'Loen Entertainment',
  제이브이엠: 'JVM',
  유니드: 'Unid',
  티씨케이: 'Tokai Carbon Korea',
  뷰웍스: 'Vieworks',
  포스코케미칼: 'POSCO Chemical',
  코리안리: 'Korean Re',
  휴젤: 'Hugel',
  한라홀딩스: 'Halla Holdings',
  아모텍: 'Amotech',
  SK오션플랜트: 'SK Oceanplant',
  롯데에너지머티리얼즈: 'Lotte Energy Materials',
  대원제약: 'Daewon Pharmaceutical',
  에스에프에이: 'SFA Engineering',
  알테오젠: 'Alteogen',
  씨앤씨인터내셔널: 'C&C International',
  동부화재: 'Dongbu Insurance',
  ISC: 'ISC',
  SGC에너지: 'SGC Energy',
  동양생명: 'Tongyang Life Insurance',
  KCC: 'KCC',
  카페24: 'Cafe24',
  엠씨넥스: 'MCNEX',
  디오: 'Dio Implant',
  경동나비엔: 'Kyungdong Navien',
  원익머트리얼즈: 'Wonik Materials',
  OCI홀딩스: 'OCI Holdings',
  시프트업: 'Shift Up',
  인바디: 'InBody',
  동성화인텍: 'Dongsung Finetec',
  미래에셋대우: 'Mirae Asset Daewoo',
  SOOP: 'SOOP',
  비에이치아이: 'BHI',
  LS산전: 'LSIS',
  서진시스템: 'Seojin System',

  /* ── 4차 보강 (2026-08-03) — 미커버 상위 130개 ───────────── */
  HD현대건설기계: 'HD Hyundai Construction Equipment',
  오스템임플란트: 'Osstem Implant',
  원익QnC: 'Wonik QnC',
  한국철강: 'Korea Iron & Steel',
  펌텍코리아: 'Pum-Tech Korea',
  대교: 'Daekyo',
  쏠리드: 'Solid',
  케이엠더블유: 'KMW',
  이노와이어리스: 'Innowireless',
  동국제강: 'Dongkuk Steel',
  SNT모티브: 'SNT Motiv',
  한올바이오파마: 'HanAll Biopharma',
  신세계푸드: 'Shinsegae Food',
  두산중공업: 'Doosan Heavy Industries & Construction',
  태광: 'Taekwang',
  웅진씽크빅: 'Woongjin ThinkBig',
  메리츠화재: 'Meritz Fire & Marine Insurance',
  아이에스동서: 'IS Dongseo',
  iM금융지주: 'iM Financial Group',
  한글과컴퓨터: 'Hancom',
  휴켐스: 'Huchems Fine Chemical',
  NEW: 'Next Entertainment World',
  티엘비: 'TLB',
  네오팜: 'Neopharm',
  효성화학: 'Hyosung Chemical',
  PI첨단소재: 'PI Advanced Materials',
  HD현대미포: 'HD Hyundai Mipo',
  산일전기: 'Sanil Electric',
  현대그린푸드: 'Hyundai Greenfood',
  에이비엘바이오: 'ABL Bio',
  AP시스템: 'AP Systems',
  인터파크: 'Interpark',
  레이언스: 'Rayence',
  한진칼: 'Hanjin KAL',
  하이비젼시스템: 'Hi Vision System',
  코오롱글로벌: 'Kolon Global',
  인탑스: 'Intops',
  HSD엔진: 'HSD Engine',
  다나와: 'Danawa',
  인터로조: 'Interojo',
  동원산업: 'Dongwon Industries',
  동국제약: 'Dongkook Pharmaceutical',
  와이솔: 'Wisol',
  인크로스: 'Incross',
  SK케미칼: 'SK Chemicals',
  동화기업: 'Dongwha Enterprise',
  포스코대우: 'POSCO Daewoo',
  한화테크윈: 'Hanwha Techwin',
  파크시스템스: 'Park Systems',
  에코마케팅: 'Eco Marketing',
  콜마비앤에이치: 'Kolmar BNH',
  롯데정보통신: 'Lotte Data Communication',
  쌍용차: 'SsangYong Motor',
  현대코퍼레이션: 'Hyundai Corporation',
  하나머티리얼즈: 'Hana Materials',
  비나텍: 'Vinatech',
  교촌에프앤비: 'Kyochon F&B',
  코리아써키트: 'Korea Circuit',
  대한제강: 'Daehan Steel',
  테크윙: 'Techwing',
  세진중공업: 'Sejin Heavy Industries',
  다산네트웍스: 'DASAN Networks',
  LF: 'LF',
  비츠로셀: 'Vitzrocell',
  슈프리마: 'Suprema',
  코미코: 'Komico',
  골프존: 'Golfzon',
  이지바이오: 'EASY BIO',
  연우: 'Yonwoo',
  현대건설기계: 'Hyundai Construction Equipment',
  휠라코리아: 'FILA Korea',
  메리츠종금증권: 'Meritz Securities',
  다음카카오: 'Daum Kakao',
  LX하우시스: 'LX Hausys',
  실리콘투: 'Silicon2',
  SPC삼립: 'SPC Samlip',
  맥쿼리인프라: 'Macquarie Korea Infrastructure Fund',
  코오롱플라스틱: 'Kolon Plastics',
  두산엔진: 'Doosan Engine',
  대한해운: 'Korea Line',
  SK디앤디: 'SK D&D',
  금호산업: 'Kumho Industrial',
  포스코켐텍: 'POSCO Chemtech',
  KB손해보험: 'KB Insurance',
  금호석유화학: 'Kumho Petrochemical',
  더블유씨피: 'WCP',
  유니셈: 'Unisem',
  에스티아이: 'STI',
  나스미디어: 'Nasmedia',
  레고켐바이오: 'LigaChem Biosciences',
  풀무원: 'Pulmuone',
  슈피겐코리아: 'Spigen Korea',
  한국단자: 'Korea Electric Terminal',
  정상제이엘에스: 'Jungsang JLS',
  루트로닉: 'Lutronic',
  일진전기: 'Iljin Electric',
  에이블씨엔씨: 'ABLE C&C',
  헥토파이낸셜: 'Hecto Financial',
  메가스터디교육: 'Megastudy Edu',
  코윈테크: 'Kowin Tech',
  헥토이노베이션: 'Hecto Innovation',
  조이시티: 'Joycity',
  '무림P&P': 'Moorim P&P',
  현대일렉트릭: 'Hyundai Electric',
  넷마블게임즈: 'Netmarble Games',
  HD현대마린솔루션: 'HD Hyundai Marine Solution',
  달바글로벌: "d'Alba Global",
  미스토홀딩스: 'Misto Holdings',
  LG씨엔에스: 'LG CNS',
  한국토지신탁: 'Korea Asset In Trust',
  티앤엘: 'T&L',
  넥스틴: 'Nextin',
  LG하우시스: 'LG Hausys',
  평화정공: 'Pyeong Hwa Automotive',
  HS효성첨단소재: 'HS Hyosung Advanced Materials',
  오스코텍: 'Oscotec',
  성광벤드: 'Sungkwang Bend',
  AJ네트웍스: 'AJ Networks',
  한국전자금융: 'Korea Electronic Financial',
  LS전선아시아: 'LS Cable Asia',
  SKC코오롱PI: 'SKC Kolon PI',
  감성코퍼레이션: 'Gamsung Corporation',
  자이에스앤디: 'Xi S&D',
  'NHN KCP': 'NHN KCP',
  지니언스: 'Genians',
  루닛: 'Lunit',
  아이패밀리에스씨: 'iFamily SC',
  텔레칩스: 'Telechips',
  선데이토즈: 'Sundaytoz',
  칩스앤미디어: 'Chips&Media',

  /* ── 5차 보강 (2026-08-03) — 미커버 상위 150개에서 **확신하는 것만** ───────
     ⚠ 9개를 일부러 뺐다 — 우주일렉트로·트루엔·아이씨티케이·한중엔시에스·
        씨어스테크놀로지·사피엔반도체·안지오랩·제노코·파인엠텍·지어소프트.
        공식 영문 표기를 확인하지 못했다. **null 이 틀린 이름보다 낫다.**
     ⚠ 「NC」도 뺐다. 엔씨소프트로 보이지만 아카이브 표기만으로는 단정할 수 없다. */
  LS에코에너지: 'LS Eco Energy',
  명신산업: 'Myoungshin Industrial',
  토비스: 'Tovis',
  보령제약: 'Boryung Pharmaceutical',
  HPSP: 'HPSP',
  KG이니시스: 'KG Inicis',
  리가켐바이오: 'LigaChem Biosciences',
  나노신소재: 'Advanced Nano Products',
  인텍플러스: 'Intekplus',
  피엔티: 'PNT',
  대한약품: 'Daehan New Pharm',
  삼진제약: 'Samjin Pharmaceutical',
  휴맥스: 'Humax',
  CJ헬로비전: 'CJ HelloVision',
  한국카본: 'Hankuk Carbon',
  엘앤씨바이오: 'L&C Bio',
  유바이오로직스: 'EuBiologics',
  티에스이: 'TSE',
  지노믹트리: 'Genomictree',
  나이스정보통신: 'NICE Information & Telecommunication',
  원텍: 'Wontech',
  브이티: 'VT',
  휴비츠: 'Huvitz',
  금화피에스시: 'Kumhwa PSC',
  NICE평가정보: 'NICE Information Service',
  쿠쿠전자: 'Cuckoo Electronics',
  제넥신: 'Genexine',
  코스모신소재: 'Cosmo AM&T',
  코스맥스엔비티: 'COSMAX NBT',
  롯데이노베이트: 'Lotte Innovate',
  라온시큐어: 'Raonsecure',
  휴메딕스: 'Humedix',
  제이앤티씨: 'JNTC',
  SAMG엔터: 'SAMG Entertainment',
  대주전자재료: 'Daejoo Electronic Materials',
  일진하이솔루스: 'Iljin Hysolus',
  SK바이오사이언스: 'SK bioscience',
  비아트론: 'Viatron Technologies',
  삼영전자: 'Samyoung Electronics',
  현대상사: 'Hyundai Corporation',
  네오위즈게임즈: 'Neowiz Games',
  한진해운: 'Hanjin Shipping',
  대한전선: 'Taihan Cable & Solution',
  태웅: 'Taewoong',
  그린플러스: 'Green Plus',
  오로스테크놀로지: 'Oros Technology',
  대양전기공업: 'Daeyang Electric',
  락앤락: 'Lock&Lock',
  HD현대: 'HD Hyundai',
  성일하이텍: 'SungEel HiTech',
  동운아나텍: 'Dongwoon Anatech',
  'HL D&I': 'HL D&I Halla',
  쏘카: 'SOCAR',
  하이록코리아: 'Hy-Lok',
  글로벌텍스프리: 'Global Tax Free',
  LG헬로비전: 'LG HelloVision',
  현대리바트: 'Hyundai Livart',
  '디앤씨미디어': 'D&C Media',
  한진: 'Hanjin Transportation',
  DL: 'DL Holdings',
  미래에셋생명: 'Mirae Asset Life Insurance',
  JW중외제약: 'JW Pharmaceutical',
  코웰패션: 'Cowell Fashion',
  한신공영: 'Hanshin Engineering & Construction',
  '서부T&D': 'Seobu T&D',
  한미글로벌: 'Hanmi Global',
  올릭스: 'OliX Pharmaceuticals',
  하나기술: 'Hana Technology',
  오이솔루션: 'OE Solutions',
  레이: 'Ray',
  마이크로디지탈: 'Microdigital',
  바디텍메드: 'Boditech Med',
  NHN한국사이버결제: 'NHN KCP',
  현대하이스코: 'Hyundai Hysco',
  IPARK현대산업개발: 'HDC Hyundai Development',
  화신: 'Hwashin',
  선익시스템: 'Sunic System',
  TKG휴켐스: 'TKG Huchems',
  서흥: 'Suheung',
  삼화콘덴서: 'Samwha Capacitor',
  에이프릴바이오: 'April Biotherapeutics',
  로보티즈: 'Robotis',
  토니모리: 'Tonymoly',
  뷰노: 'VUNO',
  대우인터내셔널: 'Daewoo International',
  에치에프알: 'HFR',
  신성이엔지: 'Shinsung E&G',
  웹케시: 'Webcash',
  노바렉스: 'Novarex',
  씨에스베어링: 'CS Bearing',
  흥국에프엔비: 'Heungkuk F&B',
  디와이파워: 'DY Power',
  디엔에프: 'DNF',
  대우증권: 'Daewoo Securities',
  BS금융지주: 'BS Financial Group',
  다음: 'Daum Communications',
  덕산하이메탈: 'Duksan Hi-Metal',
  DN오토모티브: 'DN Automotive',
  한화엔진: 'Hanwha Engine',
  엑시콘: 'Exicon',
  쿠콘: 'Coocon',
  케이아이엔엑스: 'KINX',
  피에이치에이: 'PHA',
  쇼박스: 'Showbox',
  한국자산신탁: 'Korea Asset Trust',
  상아프론테크: 'Sang-A Frontec',
  제닉: 'Genic',
  삼천리: 'Samchully',
  엠플러스: 'M Plus',
  두산테스나: 'Doosan Tesna',
  SK이터닉스: 'SK Eternix',
  쎄트렉아이: 'Satrec Initiative',
  '진성티이씨': 'Jinsung T.E.C',
  송원산업: 'Songwon Industrial',
  비올: 'Viol',
  환인제약: 'Whanin Pharmaceutical',
  제이시스메디칼: 'Jeisys Medical',
  파워로직스: 'Powerlogics',
  에스텍: 'S-Tech',
  한진중공업: 'Hanjin Heavy Industries & Construction',
  LIG손해보험: 'LIG Insurance',
  제이에스코퍼레이션: 'JS Corporation',
  HL홀딩스: 'HL Holdings',
  자화전자: 'Jahwa Electronics',
  레이크머티리얼즈: 'Lake Materials',
  빅솔론: 'BIXOLON',
  퓨쳐켐: 'FutureChem',
  펩트론: 'Peptron',
  넥슨게임즈: 'NEXON Games',
  이크레더블: 'eCredible',
  엘비세미콘: 'LB Semicon',
  이수화학: 'Isu Chemical',
  한라: 'Halla',
  뉴트리바이오텍: 'Nutribiotech',
  한국타이어월드와이드: 'Hankook Tire Worldwide',
  애경유화: 'AEKYUNG Petrochemical',
  LG생명과학: 'LG Life Sciences',
  유니테스트: 'Unitest',
  GST: 'GST',
};

/* ── DART 자동 채움 시작 · scripts/fill-subjects-from-dart.mjs 가 만든다 ──
 *
 * 출처: DART `corpCode.xml` 의 `corp_eng_name` — **회사가 금감원에 신고한 영문 법인명**이다.
 * 위의 손 사전과 달리 사람이 눈으로 확인하지 않았다. 이상한 것을 발견하면 위로 옮겨 고친다.
 *
 * ⚠ **이 선언은 지우지 않는다.** 비어 있어도 있어야 한다 —
 *   `describeSubject` 가 참조하므로 없으면 모듈이 통째로 죽는다. 실제로 한 번 그랬다.
 *   다시 만들려면 `npm run subjects:dart -- --write`.
 */
export const DART_SUBJECTS = {
  트루엔: "TRUEN Co., Ltd",
  아이씨티케이: "ICTK Co., Ltd.",
  우주일렉트로: "UJU ELECTRONICS CO., LTD",
  한중엔시에스: "HanJungNCS.Co.,Ltd",
  파인엠텍: "Fine M-Tec Co.,Ltd.",
  사피엔반도체: "Sapien Semiconductors Inc.",
  안지오랩: "AngioLab, Inc.",
  제노코: "Genohco, Inc",
  지어소프트: "GAEASOFT",
  NC: "NC Corporation",
  SNT다이내믹스: "SNT DYNAMICS CO.,Ltd",
  신흥에스이씨: "SHIN HEUNG ENERGY & ELECTRONICS CO., LTD.",
  오스테오닉: "OSTEONIC Co., Ltd.",
  와이엠티: "YMT CO., LTD.",
  범한퓨얼셀: "Bumhan Fuel Cell Co.,Ltd.",
  에스앤에스텍: "S&S TECH CORPORATION",
  플럼라인생명과학: "Plumbline Life Sciences, Inc.",
  지누스: "ZINUS INC.",
  휴온스: "HUONS CO., LTD.",
  대한조선: "DAEHAN SHIPBUILDING Co., Ltd.",
  동아쏘시오홀딩스: "Dong-A Socio Holdings Co.,Ltd",
  KG모빌리티: "KG Mobility Corp.",
  GS피앤엘: "GS P&L Co., Ltd.",
  지아이이노베이션: "GI Innovation Inc.",
  프로텍: "PROTEC Co., Ltd.",
  롯데지주: "Lotte Corporation",
  옵트론텍: "OPTRONTEC Inc.",
  에스엘에스바이오: "SLSBio(Specialty Lab Solution Bio) Co., Ltd",
  드림텍: "DREAMTECH CO.,LTD.",
  에이디테크놀로지: "ADTechnology Co., Ltd.",
  보령: "Boryung Corporation",
  디지털대성: "Digital Daesung Co., Ltd.",
  보로노이: "Voronoi, Inc.",
  이녹스: "INNOXCorporation",
  코리아에프티: "KOREA FUEL-TECH CORPORATION",
  우신시스템: "WOOSHIN SYSTEMS CO.,LTD",
  바이넥스: "Binex Co., Ltd.",
  백산: "BAIKSAN CO.,LTD",
  마크로젠: "Macrogen, Inc.",
  엘오티베큠: "LOTVacuum.Co.,Ltd.",
  바이오플러스: "BioPlus Co., Ltd",
  에스디바이오센서: "SD BIOSENSOR INC.",
  새론오토모티브: "SAERONAUTOMOTIVE CORPORRATION",
  일진홀딩스: "ILJIN HOLDINGS CO.,LTD",
  삼양사: "Samyang Corporation",
  HD현대마린엔진: "HD-Hyundai Marine Engine Co., Ltd.",
  RF머트리얼즈: "RF Materials Co., Ltd.",
  씨이랩: "XIIlab Co., Ltd",
  국도화학: "KUKDO CHEMICAL CO.,LTD",
  현대지에프홀딩스: "HYUNDAI G.F. HOLDINGS CO., LTD.",
  디케이티: "DK TECH CO.,LTD",
  오로라: "AURORA WORLD Corporation",
  세방전지: "SEBANG GLOBAL BATTERY CO.,LTD",
  일동제약: "IL DONG PHARMACEUTICAL CO., LTD.",
  케이엔제이: "KnJ Co.,Ltd.",
  KC산업: "KC INDUSTRY CO.,LTD.",
  에이치피오: "H.PIO Co., Ltd.",
  인산가: "INSAN Inc.",
  아비코전자: "ABCO ELECTRONICS CO., LTD.",
  큐렉소: "CUREXO, INC.",
  HDC: "HDC HOLDINGS CO.,Ltd",
  엠로: "EMRO., Incorporated",
  아이쓰리시스템: "i3system Inc.",
  디케이락: "DK-Lok Corporation",
  에이치시티: "HCT CO., LTD.",
  현대공업: "HYUNDAI INDUSTRIAL CO.,LTD",
  제이오: "JEIO Co., Ltd.",
  앱클론: "AbClon Inc.",
  도이치모터스: "DEUTSCH MOTORS INC.",
  NICE: "NICE Holdings Co., Ltd",
  신세계건설: "Shinsegae Engineering & Construction C.,Ltd.",
  한컴라이프케어: "Hancom Lifecare Inc.",
  HD건설기계: "HD Construction Equipment Co.,Ltd.",
  HD현대에너지솔루션: "HD HYUNDAI ENERGY SOLUTIONS CO.,LTD.",
  뉴파워프라즈마: "New Power Plasma Co.,Ltd",
  에프앤가이드: "FnGuide Inc.",
  액트로: "ACTRO CO.,Ltd",
  씨앤에스링크: "CNSLINK Co., Ltd",
  전진건설로봇: "JUNJIN CONSTRUCTION & ROBOT CO., LTD.",
  한솔홀딩스: "Hansol Holdings Co., Ltd.",
  선진뷰티사이언스: "SUNJIN BEAUTY SCIENCE CO., LTD.",
  켐트로닉스: "CHEMTRONICSCo.,Ltd.",
  듀켐바이오: "DuChemBio Co, LTD",
  나무기술: "NAMU TECH CO., LTD.",
  녹십자웰빙: "GC WellBeing Corporation",
  SNT에너지: "SNTEnergy Co.,Ltd.",
  펨트론: "PEMTRON Corporation",
  아바코: "AVACOCO.,LTD.",
  피에스케이홀딩스: "PSK HOLDINGS INC.",
  현대이지웰: "HYUNDAI EZWEL CO., LTD.",
  월덱스: "WORLDEXINDUSTRY&TRADINGCO.,LTD",
  JTC: "JTC Inc.",
  에스앤디: "S&D Co., Ltd",
  이엠티: "Energy Material Technology Co., Ltd.",
  키다리스튜디오: "KidariStudio, Inc.",
  나이스디앤비: "NICE D&B CO., LTD.",
  퍼시스: "FURSYS INC",
  씨엠에스에듀: "CMS Edu Co., Ltd.",
  한화비전: "Hanwha Vision CO.,LTD",
  비씨엔씨: "BCnC Co., Ltd.",
  디앤디파마텍: "D&D Pharmatech Inc.",
  필에너지: "PHILENERGY CO., LTD.",
  두산로보틱스: "Doosan Robotics Inc.",
  덕산테코피아: "Duksan Techopia Co., Ltd.",
  상신이디피: "SANGSINENERGYDISPLAYPRECISIONCO.,LTD",
  폰드그룹: "POND GROUP CO., LTD.",
  필옵틱스: "PHILOPTICS CO., LTD.",
  유비벨록스: "UbiVelox Inc.",
  삼천당제약: "SAM CHUN DANG PHARM CO. LTD",
  세코닉스: "SEKONIX CO., LTD.",
  큐브엔터: "CUBE ENTERTAINMENT, INC.",
  유비온: "UBION CO.LTD.",
  레드캡투어: "RedcapTour Co., Ltd.",
  쎌바이오텍: "CELL BIOTECH CO ., LTD",
  우리산업: "WOORY INDUSTRIAL CO.,LTD.",
  텔코웨어: "TELCOWARE CO.,LTD.",
  KPX케미칼: "KPX CHEMICAL CO., LTD.",
  유진기업: "EUGENE Corporation",
  해마로푸드서비스: "HAIMARROW FOOD SERVICE CO.,LTD.",
  엔에스쇼핑: "NS Shopping Co., Ltd",
  제일모직: "CHEIL INDUSTRIES INC",
  제놀루션: "GENOLUTION INC.",
  기가비스: "GigaVis Co., Ltd.",
  LIG디펜스앤에어로스페이스: "LIG Defense&Aerospace Co., Ltd.",
  제너셈: "Genesem Inc.",
  엠아이텍: "MITECH CO.,LTD.",
  넥스트바이오메디컬: "NEXTBIOMEDICAL Co., Ltd.",
  비아이매트릭스: "BI MATRIX Co., Ltd.",
  아이엠비디엑스: "IMBdx, Inc.",
  수산인더스트리: "SOOSAN INDUSTRIES CO., LTD.",
  엘리비젼: "Elivision Co., Ltd.",
  에프엔씨엔터: "FNC ENTERTAINMENT Co., Ltd.",
  질경이: "JILGYUNGYI CO.,LTD.",
  파미셀: "Pharmicell Co.,Ltd.",
  컨텍: "CONTEC Co.,Ltd",
  코텍: "KORTEK CORPORATION",
  한라IMS: "HANLA IMS Co., LTD",
  엔비티: "NBT INC.",
  에이스토리: "ASTORY Co., Ltd.",
  노머스: "Knowmerce Corp.",
  토마토시스템: "TOMATOSYSTEM Co., Ltd.",
  플리토: "Flitto Inc.",
  티이엠씨: "TEMC Co., Ltd.",
  야스: "YAS Co., Ltd",
  대원미디어: "DAEWON MEDIA CO.,LTD.",
  선진: "SUNJIN CO., LTD.",
  메드팩토: "MedPacto, Inc.",
  에코프로: "ECOPRO CO.,LTD",
  LS마린솔루션: "LS Marine Solution Co., Ltd.",
  메디젠휴먼케어: "Medizen Humancare Inc Co., Ltd",
  서연이화: "SEOYON E-HWA CO.,LTD.",
  비엠티: "BMTCo.,Ltd.",
  세경하이테크: "Se Gyung Hi Tech Co., Ltd.",
  크리스에프앤씨: "Creas F&C Co., Ltd",
  메디포스트: "MEDIPOSTCO.,LTD.",
  삼보모터스: "SAMBO MOTORS CO., LTD.",
  두올: "DUAL",
  원바이오젠: "Wonbiogen Co., Ltd.",
  이노메트리: "INNOMETRY Co., Ltd.",
  크로넥스: "CRONEX.CO.,LTD",
  코나아이: "KONA I CO., LTD.",
  제이투케이바이오: "J2KBIO Co., Ltd.",
  에스바이오메딕스: "S.Biomedics Co., Ltd.",
  싸이맥스: "CYMECHS Inc.",
  오픈엣지테크놀로지: "Openedges Technology, Inc.",
  대명에너지: "Dae Myoung Energy Co. Ltd.",
  큐리옥스바이오시스템즈: "Curiox Biosystems Co., Ltd.",
  수프로: "Suppro Co.,Ltd",
  예스티: "YEST Co.,Ltd.",
  엘티씨: "LTC CO.,LTD.",
  대성하이텍: "Daesung Hi-Tech Co., Ltd.",
  에브리봇: "EVERYBOT Inc.",
  호전실업: "Hojeon Limited",
  디아이: "DI CORPORATION",
  이노스페이스: "INNOSPACE Co., Ltd.",
  코스텍시스: "KOSTECSYS. CO., LTD.",
  선바이오: "SunBio, Inc.",
  본느: "Bonne Co., Ltd.",
  오파스넷: "OPASNET co., Ltd.",
  아진산업: "A-JIN INDUSTRY CO.,LTD",
  아모센스: "Amosense Co., Ltd.",
  티움바이오: "TiumBio Co., Ltd.",
  에프에스티: "FINE SEMITECH Corp.",
  신한알파리츠: "Shinhan Alpha REIT Co,. Ltd.",
  유비쿼스: "Ubiquoss Inc.",
  바이오다인: "BIODYNE CO., LTD.",
  큐리언트: "Qurient Co., Ltd.",
  동원개발: "DongwonDevelopment",
  랩지노믹스: "LabGenomics. Co., Ltd.",
  제이엘케이: "JLK, Inc.",
  디케이앤디: "DK&D CO.,LTD",
  나무가: "Namuga Co.,Ltd",
  테크트랜스: "Tech Trans co., Ltd",
  딥노이드: "DEEPNOID Inc.",
  제로투세븐: "Zero to Seven Inc",
  아이티엠반도체: "ITM Semiconductor Co., Ltd",
  포스코엠텍: "POSCO M-TECH CO.,LTD.",
  대동: "DAEDONG CORPORATION",
  라온테크: "raontech",
  에이플러스에셋: "A Plus Asset Advisor Co., Ltd.",
  제테마: "JETEMA Co.,Ltd.",
  신대양제지: "SHINDAEYANG PAPER CO.,LTD",
  나인테크: "Naintech. CO.,LTD.",
  아스트: "AeroSpace Technology of Korea, Inc.",
  마녀공장: "Manyo Factory Co., Ltd",
  피엔에이치테크: "P&H TECH Co., Ltd.",
  브이원텍: "V-ONE TECH CO., LTD.",
  위지윅스튜디오: "WYSIWYG STUDIOS CO., LTD.",
  툴젠: "ToolGen Incorporated",
  피엔아이컴퍼니: "PNIcompany.Co.,Ltd.",
  코메론: "KOMELON CORPORATION",
  광주은행: "The Kwangju Bank, Ltd.",
  제우스: "ZEUSCO.,LTD.",
  에스트래픽: "STraffic Co.,Ltd.",
  DMS: "DMS Co.,Ltd.",
  브이엠: "VM Inc.",
  코셈: "COXEM CO., LTD",
  쓰리에이로직스: "3ALogics. Inc.",
  에이치엔에스하이텍: "H&SHigh Tech Corp.",
  동국산업: "DONGKUK INDUSTRIES COMPANY",
  한스바이오메드: "HANS BIOMED CORPORATION",
  토모큐브: "Tomocube, Inc.",
  에프엔에스테크: "FNS TECH. Co.,Ltd.",
  엠케이전자: "MKElectron",
  머큐리: "MERCURY CORPORATION",
  에이치브이엠: "HVM CO.,LTD.",
  정다운: "JUNGDAWN Co., Ltd.",
  노바텍: "NOVATECH Co., Ltd.",
  이랜텍: "Elentec Co., Ltd",
  AP위성: "Asia Pacific Satellite lnc.",
  신테카바이오: "SyntekaBio,Inc.",
  삼일제약: "SAMIL PHARMACEUTICAL CO.,LTD",
  티에프이: "TFE Co., Ltd.",
  모트렉스: "MOTREX CO., LTD",
  대한광통신: "TAIHAN Fiberoptics Co.,LTD",
  기가레인: "GIGALANE Co., Ltd.",
  위세아이텍: "WISE iTech Co., Ltd.",
  애니플러스: "ANIPLUS INC.",
  안트로젠: "ANTEROGEN CO., LTD.",
  케이엠제약: "KMPHARMACEUTICAL Co.,Ltd.",
  이스트소프트: "ESTsoftCorp.",
  퓨런티어: "Furonteer Inc.",
  삼양패키징: "SAMYANG PACKAGING CORPORATION",
  인선이엔티: "INSUN ENVIRONMENTAL NEW TECHNOLOGY CO.",
  켐트로스: "Chemtros Co., Ltd.",
  대봉엘에스: "Daebonglsco.,Ltd",
  메디쎄이: "MEDYSSEY CO.,LTD",
  우양: "WOOYANG Co., Ltd.",
  힘스: "HIMS CO., LTD.",
  젠큐릭스: "Gencurix Inc.",
  영원무역홀딩스: "Youngone Holdings Co., Ltd",
  미래컴퍼니: "meerecompanyIncorporated",
  지앤이헬스케어: "G&E Healthcare Co., Ltd.",
  셀젠텍: "CELLGENTEK Co., Ltd",
  엔지켐생명과학: "ENZYCHEM LIFESCIENCES CORPORATION",
  한솔테크닉스: "Hansol Technics Co., Ltd",
  효성ITX: "HYOSUNG ITX.CO.,LTD",
  미스터블루: "Mr. Blue Corporation",
  경동제약: "KyungdongPharm",
  빅히트: "BIGHIT",
  제주은행: "Jeju Bank",
  일양약품: "ILYANG PHARMACEUTICAL CO.,LTD",
  크라운제과: "CROWN CONFECTIONERY CO.,LTD",
  루멘스: "LUMENS CO., LTD.",
  KG스틸: "KG DONGBUSTEEL CO., LTD.",
  큐리오시스: "Curiosis Inc.",
  코세스: "KOSES Co.,Ltd",
  세나테크놀로지: "Sena Technologies Co., Ltd.",
  미디어젠: "MediaZen, Inc.",
  지놈앤컴퍼니: "Genome&Company",
  시지트로닉스: "Sigetronics, Inc.",
  율촌: "YulChon co., Ltd",
  틸론: "TILON Co.,Ltd.",
  메쎄이상: "Messe eSang Co.,Ltd",
  다원넥스뷰: "DAWON NEXVIEW CO.,LTD.",
  위츠: "WITS Co., Ltd.",
  삼양엔씨켐: "SAMYANG NC Chem Corp.",
  지씨셀: "GC CELL CORPORATION",
  데이터스트림즈: "Data Streams Corp.",
  한국공항: "KOREA AIRPORT SERVICE CO.,LTD",
  아이마켓코리아: "iMarketKorea Inc.",
  모나용평: "MONA YONGPYONG CO.,LTD",
  STX엔진: "STX Engine Co,.Ltd",
  메가스터디: "MegaStudyCo.,Ltd.",
  태웅로직스: "Taewoong Logistics Co., Ltd.",
  큐알티: "Quality Reliability Technology Inc.",
  알지노믹스: "Rznomics Inc.",
  에이팩트: "APACT Co., Ltd.",
  컴투스홀딩스: "Com2uS Holdings Corporation",
  바이오니아: "BIONEERCORPORATION",
  우리넷: "Woori-Net Co., Ltd.",
  국순당: "KOOK SOON DANG CO.,LTD",
  에코앤드림: "Eco&Dream Co., Ltd.",
  하츠: "HAATZ Inc.",
  엠앤씨솔루션: "MNC Solution Co., Ltd",
  하이즈항공: "HIZEAERO Co.,Ltd.",
  네오셈: "Neosem Inc.",
  뉴로메카: "Neuromeka Co., Ltd.",
  샌즈랩: "SANDS LAB Inc.",
  SG: "SG CO., LTD.",
  아셈스: "ASSEMS INC.",
  이노벡스: "INNOVEX Company Limited",
  티로보틱스: "T-Robotics co., Ltd.",
  이엠넷: "EMNET INC.",
  자비스: "XAVIS CO., Ltd.",
  유엑스엔: "UXN Co., Ltd.",
  이수앱지스: "ISU Abxis Co., Ltd.",
  "세림B&G": "SERIM B&G Co.,Ltd",
  동원시스템즈: "Dongwon Systems Corporation",
  케이피에스: "KPS LTD.",
  조광페인트: "CHOKWANG PAINT CO.,LTD",
  AK홀딩스: "AK Holdings, Inc.",
  에이비온: "ABION Inc.",
  제이티: "JT Corporation.",
  카이노스메드: "KAINOS MEDICINE, INC.",
  제이씨케미칼: "JC Chemical Corporation, LTD.",
  다우기술: "DAOU TECHNOLOGY INC",
  더네이쳐홀딩스: "THE NATURE HOLDINGS CO., LTD",
  다원시스: "DAWONSYS CO., LTD",
  케이피에프: "KPF",
  인카금융서비스: "INCAR FINANCIAL SERVICE Co.,Ltd.",
  효성오앤비: "HyosungONBCo.,Ltd",
  아난티: "Ananti Inc.",
  디아이씨: "DAE-IL Corporation",
  팬엔터테인먼트: "PANENTERTAINMENTCO.,LTD.",
  SBI핀테크솔루션즈: "SBI FinTech Solutions Co., Ltd.",
  서울옥션: "SeoulAuctionCo.Ltd..",
  에코캡: "ECOCAB CO., LTD.",
  라이프사이언스테크놀로지: "Life Science Technology Inc.",
  바이오시네틱스: "Bio-Synectics, Inc.",
  디에이치피코리아: "DHP KOREA CO.LTD",
  핸즈코퍼레이션: "HANDS CORPORATION LTD.",
  한국비엔씨: "BNC KOREA, Inc.",
  플랜티넷: "PLANTYNETCo.,Ltd.",
  씨앤지하이테크: "C&G Hi Tech Co., Ltd",
  와이씨켐: "YCCHEM CO., LTD.",
  오텍: "Autech Corporation",
  지엔씨에너지: "GnCenergy Co., Ltd.",
  에스제이켐: "SJ-CHEM Co., Ltd.",
  지슨: "GITSN, Inc.",
  클로봇: "CLOBOT Co., Ltd.",
  프로티아: "PROTIA INC.",
  코어라인소프트: "Coreline Soft Co., Ltd",
  와이바이오로직스: "Y-Biologics, Inc",
  루켄테크놀러지스: "LUKEN Technologies Co., Ltd.",
  라이콤: "LiComm Co., Ltd.",
  미트박스: "MeatBox Global Inc.",
  씨알푸드: "Ssial Food Inc.",
  KX: "KX Innovation Co., Ltd.",
  우진: "WOOJIN INC",
  다날: "DANAL CO., LTD.",
  KT나스미디어: "kt nasmedia Co., Ltd.",
  파워넷: "POWERNET TECHNOLOGIES CORPORATION",
  육일씨엔에쓰: "RYUK-IL C&S., Ltd.",
  아모그린텍: "AMOGREENTECH Co., Ltd.",
  네오크레마: "Neo Cremar Co., Ltd.",
  동양이엔피: "DONGYANG E&P INC.",
  대주산업: "Daejoo Inc.",
  덱스터: "Dexter studios Co., Ltd.",
  아이디피: "IDP Corp., Ltd.",
  티에스아이: "TSI Co., Ltd.",
  나노: "NANO. Co., Ltd.",
  한양이엔지: "HANYANG ENG CO.,LTD",
  이엔에프테크놀로지: "ENF Technology Co., Ltd",
  세아메카닉스: "SeA Mechanics Co., LTD",
  이지케어텍: "ezCaretech Co., LTD",
  핑거스토리: "Finger Story CO., LTD.",
  셀비온: "Cellbion Co., Ltd",
  티쓰리: "T3 Entertainment Inc.",
  리메드: "REMED CO.,LTD.",
  이노진: "INNOGENE Co., Ltd.",
  내츄럴엔도텍: "Naturalendo Tech Co., Ltd",
  HRS: "HRS Co., Ltd",
  디티앤씨알오: "DT&CRO CO., Ltd.",
  마이크로컨텍솔: "Micro Contact Solution Co.,Ltd.",
  스튜디오미르: "Studio Mir Co., LTD.",
  오리엔탈정공: "ORIENTAL PRECISION & ENGINEERING CO.,LTD.",
  나이벡: "NIBEC CO., LTD.",
  매커스: "MAKUS Inc.",
  오리온홀딩스: "ORION Holdings Corp.",
  이엠텍: "EM-Tech.CO.,LTD.",
  엘앤케이바이오: "L&K BIOMED CO., LTD.",
  제노레이: "GENORAY Co., LTD.",
  와이엔텍: "Y-ENTECCO.,LTD.",
  케이프: "CAPE INDUSTRIES LTD.",
  아미코젠: "Amicogen, Inc.",
  아퓨어스: "APURES CO., LTD.",
  "신세계 I&C": "SHINSEGAE INFORMATION & COMMUNICATION Inc.",
  에이프로: "APRO Co., LTD",
  테고사이언스: "Tego Science, Inc.",
  TYM: "TYM CORPORATION",
  아이엘사이언스: "IL SCIENCE CO.,LTD.",
  넥스트칩: "Nextchip Co., Ltd.",
  동아엘텍: "DONGAELTEKCo.,Ltd",
  동구바이오제약: "DongKoo Bio & Pharma Co., Ltd.",
  엔브이에이치코리아: "NVH KOREA INC.",
  수젠텍: "Sugentech, Inc.",
  상신브레이크: "SANGSIN BRAKE",
  판도라티비: "PANDORA TV CO.,LTD.",
  아바텍: "AVATEC CO.,LTD.",
  큐엠씨: "QMC Co., Ltd.",
  에이스침대: "AceBed",
  디지캡: "DigiCAP Co., Ltd.",
  엔솔바이오사이언스: "Ensol Biosciences Inc.",
  이루다: "ILOODA Co.,Ltd",
  와이엠씨: "YMC Co., Ltd.",
  펨토바이오메드: "Femtobiomed Inc.",
  세운메디칼: "SEWOONMEDICAL CO,. LTD.",
  디티앤씨: "Dt&C Co., Ltd.",
  메지온: "Mezzion Pharma Co., Ltd.",
  KISCO홀딩스: "KISCO Holdings Corp.",
  풍산홀딩스: "POONGSAN HOLDINGS CORPORATION",
  두산건설: "Doosan Engineering & Construction Co.,Ltd.",
  엔에프씨: "NFC Corporation",
  삼성에피스홀딩스: "SAMSUNG EPIS HOLDINGS Co., Ltd.",
  LIG아큐버: "LIG Accuver Co.,Ltd.",
  씨어스: "SEERS Co., Ltd.",
  아이엠티: "IMT Co., Ltd.",
  에스엠씨지: "SMCG CO.,Ltd",
  성호전자: "SUNGHO ELECTRONICS CORP.",
  유라클: "URACLE. Co. Ltd",
  워트: "WOT.CO.,LTD.",
  성우테크론: "SUNGWOO TECHRON COMPANY",
  스톰테크: "Stormtec Co.,Ltd",
  젝시믹스: "XEXYMIX Corporation",
  모니터랩: "MONITORAPP CO., LTD.",
  예스24: "YES24Co.,Ltd",
  부광약품: "BUKWANG PHARMACEUTICAL IND CO.,LTD",
  고려신용정보: "Korea Credit Information CO., LTD.",
  저스템: "Justem.CO.,LTD",
  에이럭스: "ALUX Co., Ltd.",
  서플러스글로벌: "SurplusGLOBAL,Inc.",
  동인기연: "DONG IN ENTECH Co., Ltd.",
  자람테크놀로지: "Zaram Technology,Inc.",
  아이티센엔텍: "ITCENENTEC CO.,LTD.",
  금양그린파워: "KUMYANG GREEN POWER CO., Ltd.",
  코오롱: "KOLON CORPORATION",
  샘씨엔에스: "SEMCNS Co., Ltd.",
  아이스크림미디어: "i-Scream Media CO., LTD.",
  하이젠알앤엠: "HIGEN RNM CO., LTD",
  에이유브랜즈: "AU BRANDZ Co., Ltd",
  파이오링크: "Piolink, Inc.",
  오비고: "Obigo Inc.",
  코츠테크놀로지: "COTS Technology Co., Ltd.",
  네오이뮨텍: "NeoImmuneTech, Inc.",
  "와이지-원": "YG-1 CO.,LTD",
  지투파워: "G2Power Co. Ltd",
  신성에스티: "Shinsung ST Co., Ltd.",
  오킨스전자: "OKins Electronics Co.,Ltd.",
  KSS해운: "KSS LINE LTD.",
  갤럭시아머니트리: "GalaxiaMoneytree Co.,Ltd.",
  타이거일렉: "TIGER ELEC CO.,LTD.",
  미래반도체: "MIRAI SEMICONDUCTORS CO., LTD.",
  꿈비: "GGUMBI Inc.",
  솔트웨어: "Saltware Co., Ltd.",
  티앤알바이오팹: "T&R Biofab Co., Ltd",
  윤성에프앤씨: "YUNSUNG F&C Co.,Ltd",
  엔젯: "ENJET Co.,LTD",
  박셀바이오: "Vaxcell-Bio Therapeutics",
  비트컴퓨터: "BITComputer",
  오상헬스케어: "OSANG HEALTHCARE CO.,LTD.",
  미래에셋벤처투자: "Mirae Asset Venture Investment Co.,Ltd.",
  유니테크노: "UNITEKNO Co., Ltd",
  인트론바이오: "iNtRON Biotechnology, Inc.",
  서호전기: "Seoho Electric Co.,Ltd.",
  신화인터텍: "SHINWHA INTERTEK CORP.",
  HB솔루션: "HB SOLUTION CO.,LTD.",
  잉글우드랩: "Englewood Lab, Inc.",
  어보브반도체: "ABOV Semiconductor Co.,Ltd.",
  한국맥널티: "Mcnulty Korea Co., Ltd",
  청담글로벌: "CHUNGDAMGLOBAL Co., Ltd.",
  서한: "Seohan",
  아이크래프트: "iCRAFTCo.,Ltd.",
  밸로프: "VALOFE Co.,Ltd.",
  유일로보틱스: "Yuilrobotics. co., Ltd",
  성신양회: "SUNGSHIN CEMENT CO.,LTD.",
  애드바이오텍: "ADBIOTECH Co.,Ltd.",
  이노뎁: "INNODEP INC.",
  희림: "Heerim Architects & Planners",
  종근당홀딩스: "CHONGKUNDANG HOLDINGS CORP.",
  강스템바이오텍: "KANGSTEM BIOTECH CO., LTD.",
  무진메디: "Moogene Medi Co., Ltd.",
  디와이피엔에프: "DYPNF CO.,LTD",
  아스플로: "ASFLOW CO.,LTD.",
  아이디스: "INTELLIGENT DIGITAL INTEGRATED SECURITY CO., LTD.",
  바이오솔루션: "Bio Solution Co.,Ltd.",
  에스제이그룹: "SJ Group Co., Ltd.",
  신도리코: "SINDOH CO.,LTD",
  바이오인프라생명과학: "BioInfra Life Science Inc.",
  창해에탄올: "Changhae Ethanol Co., Ltd.",
  테이팩스: "TAPEX INC",
  SIMPAC: "SIMPACInc",
  푸드나무: "FOODNAMOO, INC.",
  에스엠비나: "SMVINA Co.,Ltd.",
  하림지주: "Harim Holdings Co., Ltd.",
  포시에스: "FORCS Co., Ltd.",
  아이씨디: "ICD Co.,Ltd",
  대명코퍼레이션: "Daemyung Corporation Co., Ltd",
  동아지질: "Dong-Ah Geological Engineering Company LTD.",
  에이스테크: "Ace Technologies Corp.",
  세원: "없음",
  카프로: "CAPRO CORPORATION",
  현대코퍼레이션홀딩스: "HYUNDAI CORPORATION HOLDINGS Co.,Ltd.",
  사조산업: "SAJO INDUSTRIES CO.,LTD",
  케이비캐피탈: "KB CAPITAL CO,. LTD",
  나눔테크: "NANOOMTECH Co., Ltd.",
  네패스아크: "Nepes Ark Corporation",
  인투셀: "IntoCell, Inc.",
  리더스코스메틱: "LEADERS COSMETICS CO., LTD.",
  앤씨앤: "NC& Co., Ltd.",
  에스비비테크: "SBB TECH Co., Ltd.",
  RF시스템즈: "RF Systems Co., Ltd.",
  에스티오: "STO Co., Ltd.",
  타스컴: "TASCOM Co.,Ltd.",
  스맥: "SMEC CO.,LTD",
  벡트: "VECT Co., Ltd.",
  메타바이오메드: "METABIOMED.CO.,LTD",
  블루탑: "BLUETOP CO.,LTD.",
  한국피아이엠: "PIM KOREA Co.,Ltd.",
  노브메타파마: "NovMetaPharma Co., Ltd.",
  에이펙스인텍: "APEX INTEC Co.,LTD.",
  아이케이세미콘: "IK Semicon Co., Ltd.",
  유니트론텍: "Unitrontech Co., Ltd.",
  쓰리빌리언: "3billion Inc.",
  루트락: "RootLoc Co., Ltd.",
  씨아이에스: "Creative & Innovative System Corporation",
  오르비텍: "Orbitech Co., Ltd.",
  코난테크놀로지: "KONAN TECHNOLOGY INCORPORATION",
  휴네시온: "Hunesion co.,ltd",
  삼보판지: "SAMBO CORRUGATED BOARD CO.,LTD.",
  그리티: "GRITEE, Inc.",
  "지앤비에스 에코": "GnBS eco Co.,Ltd",
  이지홀딩스: "Easy Holdings Co., Ltd.",
  지엘팜텍: "GL Pharm Tech Corp.",
  미래생명자원: "MILAE BIORESOURCES CO., LTD.",
  인벤티지랩: "Inventage Lab Inc.",
  "동국S&C": "DONGKUK STRUCTURES & CONSTRUCTION COMPANY LIMITED",
  한일사료: "HANIL FEED Co.Ltd",
  에스넷: "S NET SYSTEMS.INC",
  가온그룹: "KAON Group Co., Ltd.",
  노을: "Noul Co., Ltd.",
  피엔케이피부임상연구센타: "P&K Skin Research Center Co.,Ltd.",
  센코: "SENKO Co.,Ltd.",
  세아홀딩스: "SEAH HOLDINGS CORP",
  석경에이티: "Sukgyung AT Co., Ltd.",
  피제이메탈: "PJ METAL CO., LTD",
  진영: "JINYOUNG CO., LTD",
  티플랙스: "Tplex Co., Ltd",
  에스피소프트: "SPSoft Inc.",
  삼영: "SAMYOUNG CO.,LTD.",
  아스테라시스: "ASTERASYS Co., Ltd.",
  엔바이오니아: "Envioneer Co., Ltd.",
  타임기술: "TIME Technical Support. ltd",
  넵튠: "Neptune Company",
  대원산업: "Daewonsanup",
  메카로: "MECARO.CO.,LTD.",
  일지테크: "ILJI TECHNOLOGY CO.,LTD",
  미코: "MiCo Ltd.",
  켄코아에어로스페이스: "Kencoa Aerospace Corporation",
  재영솔루텍: "JAEYOUNG SOLUTEC CO.,LTD.",
  이니텍: "INITECH Co., Ltd.",
  아진엑스텍: "AJINEXTEK Co., Ltd.",
  싸이버원: "CyberOne Co., Ltd.",
  이랜시스: "Elensys Co.,Ltd.",
  비비씨: "Best Bristle Company Co., Ltd.",
  현대무벡스: "HYUNDAI MOVEX Co., Ltd.",
  팅크웨어: "ThinkwareSystemsCorporation",
  아나패스: "Anapass, Inc.",
  아스타: "ASTA Co., Ltd.",
  씨티케이: "CTK Co., Ltd",
  모코엠시스: "MOCOMSYS, Inc.",
  신진에스엠: "SINJIN SM CO.,LTD.",
  제일일렉트릭: "CHEIL ELECTRIC CO.,LTD.",
  제룡전기: "CHERYONG ELECTRIC CO.,LTD.",
  웨이버스: "WAVUS Co.,Ltd",
  제이아이테크: "JI-TECH Co., Ltd.",
  압타바이오: "Aptabio Therapeutics Inc.",
  라닉스: "RANIX INC.",
  시디즈: "Sidiz, Inc.",
  서원인텍: "SEOWONINTECH.CO.,LTD",
  KBI메탈: "KBI METAL CO., LTD.",
  JW생명과학: "JW LIFESCIENCE CORPORATION",
  에코플라스틱: "ECOPLASTIC CORPORATION",
  하이로닉: "Hironic Co.,Ltd",
  윈팩: "WINPAC INC.",
  브레인즈컴퍼니: "Brainzcompany Co., Ltd.",
  알리코제약: "KOREA ARLICO PHARM CO.,LTD.",
  화승알앤에이: "HWASEUNG R&A CO., LTD.",
  캠시스: "CammSys Corp.",
  아세아제지: "ASIA PAPER MANUFACTURING CO.,LTD",
  HB테크놀러지: "HB Technology CO.,LTD.",
  유아이엘: "UIL Co.,Ltd",
  포커스에이치엔에스: "FOCUS H&S CO.,LTD",
  와이아이케이: "YIK Corporation",
  한국컴퓨터: "KOREA COMPUTER INC.",
  롯데리츠: "LOTTE REIT Co., Ltd.",
  대창단조: "DAECHANG FORGING CO.,LTD",
  원준: "Onejoon Co., Ltd.",
  에어부산: "Air Busan Co., Ltd",
  유틸렉스: "Eutilex Co.,Ltd.",
  멀티캠퍼스: "Multicampus Corporation",
  코엔텍: "Korea Environment Technology Co., LTD.",
  체리부로: "Cherrybro Co.,Ltd",
  라온피플: "LaonPeople Inc.",
  키이스트: "KEYEAST Co., Ltd.",
  디피코: "DPECO CO.,LTD.",
  청광건설: "CHUNGKWANG CONSTRUCTION CO., LtD.",
  패션플랫폼: "Fashion Platform Co.,Ltd.",
  줌인터넷: "ZUM internet Corp.",
  한송네오텍: "Hansongneotech Co.,Ltd.",
  중앙백신: "CHOONG ANG VACCINE LABORATORY",
  한국유니온제약: "UNION KOREA PHARM CO.,Ltd",
  인터코스: "Interkos Co.,Ltd",
  피노텍: "Finotek Co.,Ltd.",
  티케이씨: "TKC CO., LTD.",
  네오오토: "NEOOTO CO.,LTD.",
  씨티씨바이오: "CTC BIO, INC.",
  윈스: "wins.co",
  삼기오토모티브: "SAMKEE AUTOMOTIVE CO.,LTD",
  엘아이에스: "LIS Co., Ltd.",
  솔트웍스: "Soltworks Co., Ltd.",
  휴비스: "HUVIS CORPORATION",
  한화갤러리아타임월드: "Hanwha Galleria Timeworld Co., Ltd.",
  진로발효: "JinroDistillers",
  대덕GDS: "DAEDUCK GDS CO.,LTD",
  한솔아이원스: "Hansol IONES Co., Ltd.",
  미투온: "ME2ON CO., LTD",
  제이엠멀티: "JM-MULTI",
  세아제강지주: "SeAH Steel Holdings Corporation",
  에스피지: "SPG CO., LTD",
  로체시스템즈: "RORZE SYSTEMS CORPORATION",
  아세아텍: "ASIA TECHNOLOGY Co., Ltd.",
  마이크로엔엑스: "Micro-NX Co., Ltd.",
  아이에스티이: "ISTE Co.,Ltd.",
  가온전선: "GAON CABLE CO.,LTD",
  도우인시스: "DOWOOINSYS Co., LTD.",
  에스엔시스: "S&SYS CO.,LTD",
  영화테크: "Younghwa Tech Co., Ltd.",
  에스투더블유: "S2W Inc.",
  엠에프씨: "MFC Co., Ltd.",
  셀로맥스사이언스: "Cellromax Science Co., Ltd.",
  신한글로벌액티브리츠: "Shinhan Global Active REIT Co., Ltd.",
  에르코스: "ERCOHS Agricultural Corporation Co., Ltd.",
  씨피시스템: "CP SYSTEM CO.,LTD",
  한국미라클피플사: "KOREA MIRACLE PEOPLE COMPANY Co., Ltd.",
  썬테크: "SUNTECH.CO.,LTD",
  큐라클: "curacle co., ltd.",
  엘에이티: "LAT CO., LTD.",
  KT밀리의서재: "kt millie seojae Co.,Ltd",
  HDC랩스: "HDC LABS Co., Ltd.",
  와이씨: "YC Corporation",
  씨엠티엑스: "CMTX Co.,Ltd.",
  한빛소프트: "HANBIT SOFT Inc.",
  스피어: "Sphere Corp.",
  루미르: "Lumir Inc.",
  오에스피: "OSP Co., Ltd",
  알엔투테크놀로지: "RN2 Technologies Co., Ltd.",
  라온텍: "RAONTECH INC.",
  웨이브일렉트로: "WaveElectronicsCo.,Ltd.",
  우진비앤지: "WooGeneB&GCO.,Ltd",
  에스지헬스케어: "SGHEALTHCARE CO.,LTD.",
  푸드웰: "FOODWELL CORPORATION",
  이글루: "IGLOO Corporation",
  엔시스: "Nsys Co., Ltd.",
  세종텔레콤: "Sejong Telecom, Inc.",
  삼화네트웍스: "SAMHWA NETWORKS Co.,Ltd.",
  지아이텍: "G.I.Tech Co.,Ltd.",
  네오티스: "NEOTECHNICALSYSTEMCO.,LTD",
  한독크린텍: "Handok Clean Tech Co., Ltd.",
  핑거: "Finger Inc.",
  코디: "KODI Co.,LTD.",
  성도이엔지: "SUNGDO Engineering & Construction.",
  동방메디컬: "DongBang Medical Co., Ltd.",
  알멕: "ALMAC CO., Ltd",
  시공테크: "SIGONG TECH Co.,Ltd.",
  에스오에스랩: "SOS LAB Co., Ltd.",
  슈어소프트테크: "Suresofttech Inc.",
  엑셈: "EXEM CO., LTD.",
  네온테크: "NEONTECH CO., LTD",
  탑머티리얼: "TOP MATERIAL Co., Ltd",
  제이씨현시스템: "JCH Systems, Inc.",
  퓨릿: "Purit Co., Ltd.",
  가비아: "GABIA,Inc.",
  코나솔: "KONASOL CO.,LTD",
  스마트레이더시스템: "Smart Radar System, Inc.",
  에이엘티: "ALT Co.,Ltd.",
  코아시아: "CoAsia Corporation",
  아이텍: "ITEK, Inc.",
  LB인베스트먼트: "LB Investment Inc.",
  도화엔지니어링: "DOHWA ENGINEERING Co., Ltd.",
  와이투솔루션: "Y2 Solution CO.,LTD",
  큐에스아이: "Q.S.ICo.,Ltd.",
  현우산업: "HYUNWOOINDUSTRIALCO.,LTD",
  제일테크노스: "JEIL TECHNOS CO.,LTD",
  아이앤씨: "I&C Technology Co., Ltd.",
  위지트: "WIZIT Co., Ltd.",
  새로닉스: "SERONICS. CO., LTD.",
  한국팩키지: "HANKUK PACKAGE CO., LTD.",
  미래나노텍: "MNTECHCo.,Ltd.",
  더블유에스아이: "WSI Co., Ltd.",
  아시아종묘: "ASIA SEED Co.,Ltd.",
  삼영에스앤씨: "SAMYOUNG S&C CO., LTD.",
  아이티아이즈: "ITEYES Inc.",
  로보스타: "Robostar Co.,Ltd.",
  한일단조: "HanilForgingIndustrial",
  삼보산업: "SAMBO Industrial Co., Ltd.",
  비큐AI: "BECU AI Inc.",
  SGA솔루션즈: "SGA Solutions Co.,Ltd.",
  이엘피: "ELP Corp.",
  피앤씨테크: "PNC Technologies Co.,Ltd.",
  솔트룩스: "SALTLUX Inc",
  한화리츠: "Hanwha REIT Co., Ltd.",
  벽산: "BYUKSAN CORPORATION",
  삼진엘앤디: "SAMJIN LND COMPANY LIMITED",
  한국앤컴퍼니: "HANKOOK & COMPANY CO., LTD.",
  오디텍: "ODTech",
  동양에스텍: "Dongyang S·TEC Co., Ltd.",
  동방선기: "Dongbang Ship Machinery Co., Ltd",
  디아이티: "DIT Corp.",
  제주반도체: "Jeju Semiconductor Corp.",
  삼기: "SAMKEE CORP.",
  한국파마: "KOREA PHARMA Co., Ltd.",
  이엠코리아: "ELECTRIC MOTORS KOREA CO., LTD",
  이노인스트루먼트: "INNO INSTRUMENT INC.",
  엔텔스: "nTelsCo.,Ltd.",
  셀리드: "Cellid Co., Ltd.",
  플라즈맵: "Plasmapp Co., Ltd.",
  에스피시스템스: "SP SYSTEMS CO.,LTD.",
  구영테크: "GUYOUNG TECHNOLOGY CO., LTD.",
  태양기계: "Sun Machinery Co.,LTD",
  팜스토리: "FarmStory CO.,LTD.",
  뉴트리: "Newtree Co., Ltd.",
  엠투엔: "M2N Co.,Ltd",
  옵티팜: "Optipharm.CO.,LTD",
  서울바이오시스: "SEOUL VIOSYS CO., LTD.",
  삼화전기: "SAMWHA ELECTRIC CO.,LTD",
  종근당바이오: "CKD Bio Corp.",
  싸이토젠: "Cytogen, Inc.",
  탑코미디어: "Topco Media Co.,Ltd.",
  시그네틱스: "Signetics Corp.",
  하나제약: "Hana Pharm. Co., Ltd.",
  보광산업: "BOKWANG INDUSTRY CO.,LTD",
  진양제약: "JIN YANG PHARMACEUTICAL. CO., LTD",
  프로이천: "PRO2000 CO.,LTD.",
  라파스: "Raphas Co., Ltd.",
  나노엔텍: "NanoenTek,Inc.",
  알에스오토메이션: "RS AUTOMATION CO.,LTD.",
  지에스이: "GSE Co., Ltd.",
  씨큐브: "CQV Co., Ltd.",
  나라소프트: "NARASOFT Co.,Ltd.",
  인바이츠바이오코아: "INVITES BIOCORE CO., LTD",
  파인테크닉스: "FINE TECHNIX CO., LTD",
  나라엠앤디: "NARA MOLD AND DIE CO., LTD.",
  엔케이맥스: "NKMAX Co.,Ltd.",
  MDS테크: "MDS Tech Inc.",
  윈하이텍: "WINHITECH CO., Ltd.",
  시노펙스: "Synopex Inc.",
  알로이스: "ALOYS Inc.",
  압타머사이언스: "Aptamer Sciences Inc",
  국영지앤엠: "KUK YOUNG G M",
  원티드랩: "Wanted Lab Inc.",
  이리츠코크렙: "E KOCREF CR-REIT",
  토박스코리아: "TOEBOX KOREA, Ltd.",
  엠에프엠코리아: "MFM KOREA Co., Ltd.",
  케어랩스: "Carelabs Co.,Ltd",
  메리츠증권: "MERITZ SECURITIES CO.,LTD",
  노루페인트: "NOROO PAINT & COATINGS Co.,LTD",
  노드메이슨: "Nordmason Co.,LTD",
  에이치엘사이언스: "HLSCIENCE Co., LTD",
  아이스크림에듀: "i-Scream Edu Co., Ltd.",
  캐스텍코리아: "CASTEC KOREA CO.,LTD",
  코리아센터: "Koreacenter Co.,Ltd.",
  모바일어플라이언스: "MOBILE APPLIANCE, INC.",
  메디안디노스틱: "Median Diagnostics Inc.",
  팜스빌: "Pharmsville Co., Ltd.",
  엔에스: "NS Co.,Ltd.",
  엠에스오토텍: "MS AUTOTECH COMPANY, LIMITED",
  덕우전자: "DERKWOO ELECTRONICS CO.,LTD.",
  해성옵틱스: "Haesung Optics Co.,Ltd",
  명진홀딩스: "Myungjin Holdings.,Corp.",
  앙츠: "Antz. Co., Ltd",
  지엠피: "GMP Co., Ltd.",
  볼빅: "VOLVIK INC.",
  NHN벅스: "NHN BUGS Corporation",
  잇츠한불: "IT'S HANBUL CO., LTD.",
  남양유업: "NAMYANG DAIRY PRODUCTS CO.,LTD",
  피에스텍: "PS Tec. Co., Ltd.",
  대신증권: "DAISHIN SECURITIES CO.,LTD",
  엔비알모션: "NBR Motion Co., Ltd.",
  오리엔트정공: "Orient Precision Industries Inc.",
  삼아알미늄: "SAMA ALUMINIUM CO.,LTD",
  컬러레이: "Coloray International Investment Co., Limited",
  일진파워: "ILJIN POWER CO., LTD.",
  제이에스링크: "JS Link, Inc.",
  그래피: "Graphy Inc.",
  바스칸바이오제약: "BASKHANBIOPharma Inc.",
  삼미금속: "Sammi Metal Products Co., Ltd.",
  이상네트웍스: "eSANGNetworksCo.,Ltd",
  에코프로에이치엔: "ECOPRO HN CO., LTD",
  동일금속: "DONGIL METAL CO., LTD.",
  E8: "E8 Co.,Ltd.",
  KX하이텍: "KX HITECH CO.,LTD",
  리브스메드: "LivsMed Inc.",
  아하: "AHA Co.,Ltd",
  LS머트리얼즈: "LS Materials Co.,Ltd.",
  피앤에스로보틱스: "P&S Robotics Co., Ltd.",
  HEM파마: "HEM Pharma Inc.",
  아이티센피엔에스: "ITCENPNS CO.,LTD.",
  시선AI: "SECERN AI Co., Ltd.",
  큐라켐: "CURACHEM Co., ltd.",
  뱅크웨어글로벌: "Bankware Global Co., Ltd.",
  에임드바이오: "Aimed Bio Inc.",
  서울보증보험: "Seoul Guarantee Insurance Company",
  온코크로스: "Oncocross Co.,Ltd.",
  아이비김영: "IBKIMYOUNG CO.,LTD.",
  티엘엔지니어링: "TL Engineering Co., Ltd.",
  한텍: "HANTECH LTD.",
  와이즈넛: "WISEnut, INC.",
  심플랫폼: "Simplatform Co., Ltd.",
  HJ중공업: "HJ SHIPBUILDING & CONSTRUCTION CO.,LTD",
  지에프씨생명과학: "GFC Life Science Co., Ltd.",
  태양3C: "3C TAE YANG CO., LTD.",
  국일신동: "KUKIL METAL CO., LTD",
  모델솔루션: "Model Solution Co., Ltd.",
  "SM Life Design": "SM Life Design Group Co., Ltd.",
  잉크테크: "INKTEC CO., LTD.",
  케이씨피드: "KC FEED CO., LTD.",
  삼양컴텍: "SAMYANG COMTECH CO., LTD.",
  KT지니뮤직: "KT GENIE MUSIC CORPORATION",
  한국정보통신: "KoreaInformation&Communication",
  파이버프로: "FIBERPRO, Inc.",
  현대바이오랜드: "HYUNDAI BIOLAND Co.,Ltd.",
  하림: "HARIM Co., Ltd.",
  광주신세계: "GwangjuShinsegae. Co.,Ltd.",
  우진엔텍: "WOOJIN Ntec Inc.",
  이지트로닉스: "EGTRONICS Co., Ltd.",
  엠에스씨: "MSC Co.,Ltd.",
  SJG세종: "SJG SEJONG CO.,LTD",
  링네트: "RingNet Co., Ltd.",
  세보엠이씨: "SEBO MANUFACTURING ENGINEERING CORPORATION",
  오가노이드사이언스: "ORGANOIDSCIENCES LTD.",
  코칩: "KORCHIP CORPORATION",
  에코프로머티: "ECOPRO MATERIALS CO., LTD.",
  닷밀: "dotmill Inc.",
  엔젠바이오: "NGeneBio Co., Ltd.",
  한국알콜: "KoreaAlcoholIndustrial",
  드림씨아이에스: "DreamCIS INC.",
  드림인사이트: "DREAMINSIGHT Co., Ltd.",
  벨로크: "Bellock Inc.",
  지오엘리먼트: "GO Element Co., Ltd.",
  바이젠셀: "ViGenCell Inc.",
  에이텍: "ATEC CO.,Ltd",
  한국정보인증: "KOREA INFORMATION CERTIFICATE AUTHORITY, INCORPORATED",
  비피도: "BIFIDO. Co. Ltd",
  에이에스텍: "ASTech Co., Ltd.",
  KR모터스: "KR MOTORS CO., LTD",
  트윔: "TWIM Corp",
  모토닉: "MOTONIC CORPORATION",
  "형지I&C": "HYUNGJI Innovation and Creative Company Limited",
  유니크: "UNICK CORPORATION",
  로보로보: "RoboRobo Co., Ltd.",
  옵티시스: "OPTICIS CO., LTD.",
  소프트캠프: "SOFTCAMP Co., Ltd.",
  유비쿼스홀딩스: "Ubiquoss Holdings Inc.",
  아이오바이오: "AIOBIO Co., Ltd.",
  현대에버다임: "HYUNDAI EVERDIGM Corp.",
  신화콘텍: "Shin Hwa Contech Co.,Ltd.",
  자연과환경: "NatureandEnvironmentCo.,Ltd.",
  케이씨티: "Korea Computer Terminal Inc.",
  플레이위드: "PLAYWITH KOREA Inc.",
  멕아이씨에스: "MEKICS Co., Ltd",
  유라테크: "YURA TECH. CO., LTD.",
  타이드: "TIDE Co., Ltd.",
  동양파일: "TONGYANG PILE Inc.",
  삼지전자: "SAMJI ELECTRONICS CO., LTD.",
  영우디에스피: "YoungWoo DSP Co.,Ltd.",
  대신정보통신: "DaishinInformation",
  럭스피아: "Luxpia Co., Ltd.",
  포인트모바일: "POINT MOBILE Co., Ltd.",
  원익: "WonIk Co.,LTD",
  "SG&G": "SG&G Corporation",
  코데즈컴바인: "Codes Combine Co.,Ltd.",
  특수건설: "TuksuConstruction",
  에쎈테크: "ESSEN TECH CO.,LTD.",
  원풍: "WonpoongCorporation",
  피코그램: "picogram Co., Ltd.",
  보성파워텍: "BOSUNG POWER TECHNOLOGY CO., LTD.",
  크린앤사이언스: "Clean & Science Co., Ltd",
  탈로스: "Talos Co., Ltd.",
  안국약품: "AHN-GOOK PHARMACEUTICAL Co., Ltd.",
  코이즈: "KOYJ. CO.,LTD",
  애니메디솔루션: "anymedi Inc.",
  대아티아이: "DAEA TI CO., LTD.",
  케이엔알시스템: "KNR SYSTEMS Inc.",
  에코아이: "ECOEYE CO., LTD.",
  노랑풍선: "Yellow Balloon Tour Co., Ltd.",
  브리지텍: "BRIDGETECCorp.",
  에스알바이오텍: "SR biotek Inc.",
  윙스풋: "WING'S FOOT INC.",
  포바이포: "4by4 Inc.",
  노브랜드: "Nobland International Inc.",
  서진오토모티브: "Seojin Automotive Co.,Ltd.",
  대림제지: "DaelimPaper",
  코스텍시스템: "Kostek Systems, Inc.",
  EMB: "EMB CO.,LTD.",
  바이브컴퍼니: "VAIV company Inc.",
  링크제니시스: "Linkgenesis Co., Ltd.",
  셀바스AI: "SELVAS AI Inc.",
  경창산업: "KyungchangIndustrial",
  동국씨엠: "DONGKUK COATED METAL Co., Ltd.",
  아톤: "ATON Inc.",
  파인디지털: "FINEDIGITAL Inc.",
  유유제약: "Yuyu Pharma, Inc.",
  인지디스플레: "INZI DISPLAY COMPANY LIMITED",
  다보링크: "DAVOLINK Inc.",
  제룡산업: "CHERYONG INDUSTRIAL CO.,LTD.",
  팜젠사이언스: "PharmGen Science, Inc.",
  넥스틸: "NEXTEEL CO.,LTD.",
  비스토스: "Bistos Co., Ltd.",
  부스타: "BOOSTER CO., LTD.",
  대원강업: "DAEWONKANGUP CO.,LTD",
  아이엠: "IMCo.,LTD",
  비상교육: "VISANG EDUCATION INC",
  듀오백: "DUOBACK CO., LTD.",
  경남스틸: "Kyeong Nam Steel Co., LTD",
  앱코: "ABKO CO., LTD.",
  픽셀플러스: "Pixelplus. Co., Ltd.",
  디에이피: "DAP Co., Ltd",
  고스트스튜디오: "GHOST STUDIO CO., LTD.",
  케이에스피: "KSPCO.,LTD",
  폴라리스오피스: "Polaris Office Corp.",
  남해화학: "NAMHAE CHEMICAL CORPORATION",
  엔에스컴퍼니: "NSCompany CO., LTD.",
  램테크놀러지: "RAM TECHNOLOGY CO., LTD.",
  세명전기: "SemyungElectricMachinery",
  씨앗: "CIAAT Co., Ltd.",
  이화공영: "EehwaConstruction",
  넥스트아이: "NextEye Co., Ltd.",
  크리스탈신소재: "China Crystal New Material Holdings Co., Ltd.",
  에스에스알: "SSR Inc.",
  동일철강: "DONGIL STEEL CO., LTD",
  제이스텍: "JESTEC.CO.LTD",
  소마젠: "Psomagen, Inc.",
  서희건설: "SEOHEE CONSTRUCTION CO., LTD.",
  드림시큐리티: "Dream Security Co.,Ltd.",
  국보디자인: "KUKBO DESIGN",
  코퍼스코리아: "COPUS KOREA Co., Ltd.",
  덴티스: "DENTIS CO.,LTD",
  태경케미컬: "TAEKYUNG CHEMICAL CO.,LTD",
  굿센: "GoodSSEN Co.,Ltd",
  지엠비코리아: "GMB Korea Corp.",
  대보마그네틱: "DAEBO MAGNETIC CO.,LTD.",
  유진로봇: "Yujin Robot Co., Ltd.",
  러셀: "RUSSELL CO., LTD.",
  EDGC: "Eone Diagnomics Genome Center Co., Ltd.",
  디씨엠: "DCM CORP",
  베셀: "Vessel Co., Ltd.",
  황금에스티: "Hwang Kum Steel & Technology Co., Ltd",
  케이엔더블유: "KNW Co., Ltd.",
  파버나인: "PAVONINE CO., LTD.",
  아이큐어: "Icure Pharmaceutical Incorporation",
  대모: "DAEMO Engineering Co., Ltd.",
  보라티알: "BORATR CO., Ltd.",
  고려시멘트: "KOREA CEMENT co., Ltd",
  이트론: "E-TRON CO.,LTD.",
  휴마시스: "HUMASIS CO., LTD.",
  쎄노텍: "CENOTEC Co., Ltd",
  아우딘퓨쳐스: "Outin Futures Co., Ltd.",
  서전기전: "SEOJEON ELECTRIC MACHINERY Co.,Ltd.",
  한국선재: "HANKUK STEEL WIRE CO., LTD.",
  대유: "DAEYU CO., LTD.",
  바이오톡스텍: "BiotoxtechCo.,Ltd.",
  흥국: "HEUNGKUK METALTECH CO.,LTD.",
  코콤: "KOCOM CO., LTD",
  녹십자엠에스: "GC Medical Science Corporation",
  파세코: "PASECO CO.LTD",
  이즈미디어: "isMedia Co., Ltd",
  화일약품: "HWAIL PHARM. CO., LTD",
  삼진: "Samjin",
  데이타솔루션: "Datasolution, Inc.",
  "SM C&C": "SM Culture & Contents Co., Ltd.",
  피씨엘: "PCL. Inc",
  파라텍: "Paratech Company Limited",
  세종메디칼: "SEJONG MEDICAL Co.Ltd.,",
  KCC건설: "KCC ENGINEERING & CONSTRUCTION CO., LTD.",
  에이티세미콘: "JHCOS Co., Ltd.",
  에스폴리텍: "S POLYTECH CO.,LTD.",
  프로스테믹스: "PROSTEMICS Co.Ltd.",
  노루홀딩스: "NOROO HOLDINGS CO., LTD",
  유앤아이: "UNI",
  셀리버리: "Cellivery Therapeutics, Inc.",
  파워풀엑스: "Power Fulx Co., Ltd.",
  드래곤플라이: "Dragonfly GF Co., Ltd.",
  세화피앤씨: "SEWHA P&C INC.",
  필링크: "FILINK Co., Ltd",
  코스모화학: "COSMOCHEMICALCO.,LTD",
  이에스산업: "ES INDUSTRY CO.,LTD",
  미애부: "Miev Co., Ltd.",
  SBS미디어홀딩스: "SBS Media Holdings",
  삼성출판사: "SAMSUNG PUBLISHING CO.,LTD",
  대주이엔티: "Daejoo Energy INnovation Technology Co.,Ltd",
  예림당: "YeaRimDang Publishing Co., Ltd.",
  선광: "SUN KWANG Co.,Ltd",
  예선테크: "YeSUN Tech Co., Ltd.",
  현대차증권: "HYUNDAI MOTOR SECURITIES CO.,LTD.",
  에이엔피: "AUTOMOBILE & PCB",
  DXVX: "Dx & Vx Co., Ltd.",
  케이피엠테크: "KPM TECH CO., LTD.",
  엔알비: "NRB, inc",
  PS일렉트로닉스: "Pentastone Electronics, Inc.",
  KTis: "ktis Corporation",
  한솔홈데코: "Hansol HomeDeco co.,ltd.",
  아크릴: "Acryl Inc.",
  쏘닉스: "SAWNICS INC.",
  인스피언: "Inspien, Inc.",
  오름테라퓨틱: "Orum Therapeutics, Inc.",
  한국정밀기계: "HNK MACHINE TOOL CO.,LTD.",
  에스코넥: "S Connect Co., LTD",
  에스와이: "SY CO., LTD.",
  유비씨: "UVC Co., Ltd.",
  로킷헬스케어: "ROKIT HEALTHCARE Inc.",
  나우로보틱스: "NAUROBOTICS Co., Ltd.",
  유디엠텍: "UDMTEK Co.,Ltd.",
  성우: "SUNGWOO CO., LTD",
  알트: "ALT Co., Ltd.",
  키스트론: "KISTRON Co., Ltd.",
  티엠씨: "TMC Co., Ltd.",
  데이원컴퍼니: "Day1 Company Inc.",
  지투지바이오: "G2GBIO, Inc.",
  오아: "OA Co., Ltd.",
  제이피아이헬스케어: "JPI Healthcare Co., Ltd.",
  바이오텐: "Bioten Co., Ltd",
  쎄크: "SEC co.,ltd.",
  GS글로벌: "GS Global Corp.",
  뉴로핏: "NEUROPHET Inc.",
  엘케이켐: "LK CHEM Co., Ltd.",
  미쥬: "Miju Co., Ltd.",
  온코닉테라퓨틱스: "Onconic Therapeutics Inc.",
  HLB이노베이션: "HLB innoVation Co.,Ltd.",
  나라스페이스테크놀로지: "Nara Space Technology Inc.",
  엑사이엔씨: "EXA E&C, Inc",
  베노티앤알: "BENO TNR, Inc.",
  인성정보: "INSUNG INFORMATION CO., LTD",
  태양: "TAEYANG Corporation",
  엠아이큐브솔루션: "MICUBE SOLUTION, INC.",
  디지아이: "Digital Graphics Incorporation",
  M83: "M eighty-three Co.,Ltd.",
  매일홀딩스: "MAEIL HOLDINGS CO., LTD.",
  메가엠디: "MegaMD Co., Ltd.",
  "비보존 제약": "VIVOZON PHARMACEUTICAL CO., LTD.",
  HC홈센타: "HC HomeCenter Co.,Ltd",
  하스: "HASS Corp.",
  자이언트스텝: "GIANTSTEP Inc.",
  아이티센글로벌: "ITCENGLOBAL CO.,LTD.",
  빅텍: "VICTEK. Co., Ltd.",
  핸디소프트: "HandySoft Corp.",
  SCL사이언스: "SCL Science Inc.",
  티에이치엔: "THN CORPORATION",
  옵티코어: "OptiCore Inc.",
  이엔셀: "ENCell Co., Ltd.",
  크레버스: "Creverse, Inc.",
  무림SP: "MOORIM SP CO., LTD.",
  케이지에이: "KGA CO., LTD",
  케이엔솔: "K-ENSOL CO., LTD.",
  탑런토탈솔루션: "TOP RUN TOTAL SOLUTION CO.,LTD",
  라온로보틱스: "RAON ROBOTICS Inc.",
  피엠티: "Protec Mems Technology Inc.",
  우리손에프앤지: "Woorison F&G CO., LTD.",
  지니너스: "GENINUS Inc.",
  넥센: "NEXEN CORPORATION",
  코닉오토메이션: "Kornic Automation Co.Ltd.",
  신스틸: "SHIN STEEL CO.,LTD.",
  링크솔루션: "LINCSOLUTION CO., LTD.",
  이엠앤아이: "EMnI Co., Ltd.",
  금비: "KUMBI CO.,LTD",
  "SUN&L": "SUN&L CO.,LTD",
  SK시그넷: "SK Signet Inc.",
  민테크: "Mintech Co., Ltd.",
  퀄리타스반도체: "QUALITAS SEMICONDUCTOR CO., LTD.",
  한성크린텍: "HANSUNG CLEANTECH CO., LTD.",
  유니퀘스트: "UNIQUEST COPORATION",
  디와이: "DY Corporation",
  대한화섬: "DAEHAN SYNTHETIC FIBRER CO.,LTD",
  에스엠벡셀: "SM BEXEL CO.,LTD",
  네이블: "Nable Inc.",
  모비스: "Mobiis Co., Ltd.",
  티피씨글로벌: "TPC CO., LTD",
  에스에이티: "SystemandApplicationTechnologiesInc.",
  티사이언티픽: "T Scientific Co.,Ltd",
  미래산업: "MIRAE CORPORATION",
  콜마홀딩스: "KOLMAR HOLDINGS CO.,LTD.",
  제이엠티: "JMT CO.,Ltd.",
  케이옥션: "K Auction Inc.",
  대창: "DAECHANG Co.,Ltd",
  진흥기업: "CHINHUNG INTERNATIONAL INC",
  딜리: "DILLI ILLUSTRATE INC.,",
  광동헬스바이오: "Kwangdong Healthbio Co., Ltd.",
  더즌: "Dozn Inc.",
  인터엠: "IntermCorporation",
  레이저옵텍: "Laseroptek Co., Ltd.",
  위메이드플레이: "Wemade Play Co., Ltd.",
  나노팀: "NanoTIM Co. Ltd.",
  남광토건: "NAMKWANG ENGINEERING & CONSTRUCTION CO.,LTD",
  한창제지: "HANCHANG PAPER CO.,LTD",
  오리엔트바이오: "ORIENTBIO Inc.",
  아이엘: "IL CO.,LTD.",
  케이사인: "KSIGN CO., Ltd.",
  엔에스엠: "NSM CO.,LTD.",
  라메디텍: "LAMEDITECH Co., Ltd.",
  대동스틸: "DAE DONG STEEL CO., LTD.",
  오상자이엘: "OSANGJAIEL Co., Ltd",
  한라캐스트: "HALLACAST Co.,Ltd",
  더콘텐츠온: "The Contents On Co., Ltd.",
  아이디스홀딩스: "IDIS Holdings Co., Ltd",
  화인베스틸: "FINEBESTEEL CO., LTD",
  PN풍년: "PNPOONGNYUN CO.,LTD",
  엠젠솔루션: "MGEN SOLUTIONS CO., LTD.",
  제이에스티나: "J.ESTINA Co.,Ltd",
  서린바이오: "SeouLinBioscienceCO.,LTD.",
  케이엠: "KM CORPORATION",
  누리플랜: "Nuriplan Co.,Ltd.",
  모다이노칩: "Moda-InnoChips Co., Ltd.",
  삼일: "SamIl",
  피아이이: "PIE CO., LTD.",
  한국정보공학: "Korea Information Engineering Services Co., Ltd",
  동일고무벨트: "DRB Industrial Co.,Ltd",
  텔콘RF제약: "TELCON RF PHARMACEUTICAL. Inc.",
  아이즈비전: "EYESVISION CORPORATION",
  프로젠: "ProGen, Co,, LTD.",
  모아텍: "MOATECH CO., LTD.",
  바이오포트: "BIO PORT KOREA, INC.",
  오리콤: "ORICOM Inc",
  우리로: "WOORIRO CO., LTD",
  아이씨에이치: "ICH Co., Ltd.",
  폴라리스우노: "POLARIS UNO, Inc.",
  뉴보텍: "NUVOTEC Co., Ltd",
  비투엔: "B2En Co., Ltd.",
  모아데이타: "Moadata Co., Ltd.",
  엔피케이: "NPK CO.,LTD",
  에스와이스틸텍: "SY STEEL TECH, Inc.",
  누보: "NOUSBO CO., LTD",
  한주라이트메탈: "HANJOO LIGHT METAL CO., LTD.",
  경농: "KYUNGNONG CORPORATION",
  진양산업: "CHIN YANG INDUSTRY CO.,LTD.",
  유엔젤: "UANGEL CORPORATION",
  레인보우로보틱스: "Rainbow Robotics",
  엔젤로보틱스: "ANGEL ROBOTICS Co., Ltd.",
  LB세미콘: "LB SEMICON, INC.",
  세니젠: "SANIGEN Co., Ltd.",
  빛샘전자: "VISSEM Electronics Co., Ltd.",
  다우데이타: "DAOU DATA CORP.",
  이건홀딩스: "EAGON HOLDINGS CO., LTD.",
  원포유: "ONE4U CO.,LTD",
  진코스텍: "JINCOSTECH CO.,LTD.",
  와이어블: "Wiable Corp.",
  KG케미칼: "KG Chemical Corporation",
  휴스틸: "HUSTEEL CO.,LTD",
  레뷰코퍼레이션: "RevuCorporation Inc",
  사이냅소프트: "Synapsoft Corp.",
  고려산업: "KOREA INDUSTRIAL CO.,LTD",
  마음AI: "MAUM.AI, INC.",
  큐로셀: "Curocell Inc.",
  이구산업: "LEEKU INDUSTRIAL CO.,LTD",
  에이직랜드: "ASICLAND Co.,Ltd",
  대원전선: "DAWON CABLE CO.,LTD",
  NI스틸: "NI STEEL CO.,LTD",
  코오롱모빌리티그룹: "KOLON MOBILITY GROUP CORPORATION",
  태림포장: "Tailim Packaging Co., Ltd",
  샤페론: "Shaperon Inc.",
  팸텍: "PAMTEK CO., LTD.",
  제일엠앤에스: "JEIL M&S CO., LTD",
  블루엠텍: "BLUEMTEC CO., LTD.",
  광동제약: "KWANGDONG PHARMACEUTICAL CO.,LTD",
  이브이첨단소재: "EV ADVANCED MATERIAL CO., LTD.",
  엠게임: "MGAME CORP.",
  엑스게이트: "AXGATE Co., Ltd.",
  현대힘스: "HYUNDAI HYMS CO., LTD.",
  "CJ 바이오사이언스": "CJ Bioscience",
  케이엔에스: "KNS CO., LTD",
  화승코퍼레이션: "Hwaseung Corporation CO., LTD",
  플래티어: "Plateer Co., Ltd.",
  파인디앤씨: "FINE DNC CO.,LTD.",
  셀바이오휴먼텍: "Cell Bio Human Tech Co., Ltd",
  플레이디: "PlayD Co., Ltd.",
  마이크로투나노: "MICRO2NANO, INC.",
  삼영엠텍: "SAMYOUNG M-TEK C0. LTD.",
  일진디스플: "ILJIN DISPLAY CO.,LTD.",
  오스템: "AUSTEM CO.,LTD",
  바이오에프디엔씨: "BIO-FD&C CO.,LTD.",
  와이엠텍: "YM Tech Co., Ltd.",
  사조대림: "SAJODAERIM CORPORATION",
  포스코스틸리온: "POSCO STEELEON Co.,Ltd.",
  카이바이오텍: "KaiBioTech Co., Ltd",
  영림원소프트랩: "YoungLimWon SoftLab. Co., Ltd.",
  우리산업홀딩스: "WOORY INDUSTRIAL HOLDINGS CO.,LTD.",
  핀텔: "Pintel Co.,Ltd.",
  국전약품: "Kukjeon Pharm Co.,Ltd.",
  뉴프렉스: "NEWFLEXTECHNOLGYCo.,LTD.",
  페이퍼코리아: "PaperCorea Inc.",
  리파인: "REFINE Co., Ltd.",
  퓨쳐메디신: "Future Medicine Co., Ltd.",
  센서뷰: "SENSORVIEW CO., LTD.",
  삼익THK: "SAMICK THK CO.,LTD",
  우림피티에스: "WOORIM POWER TRAIN SOLUTION Co., Ltd.",
  에피바이오텍: "Epi Biotech Co., Ltd.",
  알서포트: "RSUPPORT Co., Ltd.",
  켈스: "CALTH. Inc",
  우리기술: "Woori Technology, Incorporation",
  일신방직: "ILSHIN SPINNING CO.,LTD",
  와이랩: "YLAB Corporation",
  이노시뮬레이션: "INNOSIMULATION CO., LTD.",
  엔켐: "Enchem Co., Ltd.",
  에이테크솔루션: "A-Tech Solution CO., LTD.",
  ESR켄달스퀘어리츠: "ESR Kendall Square REIT Co., Ltd.",
  코람코라이프인프라리츠: "KORAMCO LIFE INFRA REIT CO.,LTD",
  산돌: "Sandoll, Inc.",
  유티아이: "UTI INC.",
  유수홀딩스: "EUSU HOLDINGS CO., LTD.",
  피델릭스: "Fidelix Co., Ltd.",
  전진바이오팜: "JEONJINBIO CO., LTD.",
  엄지하우스: "EOMJIHOUSE Co., Ltd",
  나노씨엠에스: "NANOCMS CO., LTD",
  이미지스: "IMAGIS Co., Ltd.",
  아이퀘스트: "IQUEST Co., Ltd.",
  코오롱생명과학: "KOLON LIFE SCIENCE Inc.",
  조아제약: "ChoA Pharmaceutical Co., LTD.",
  프리시젼바이오: "Precision Biosensor Inc.",
  삼륭물산: "Samryoong",
  이앤에치: "E&H Co., Ltd.",
  원익홀딩스: "WONIK HOLDINGS CO.,LTD.",
  기산텔레콤: "Kisan Telecom CO., Ltd.",
  이성씨엔아이: "IHSUNGCNI CO.,LTD.",
  원풍물산: "WonpungMulsan",
  스코넥: "SKONEC ENTERTAINMENT Co., Ltd.",
  에이디칩스: "Advanced Digital Chips Inc.",
  사조씨푸드: "SAJO SEA FOOD CO.,LTD",
  한국종합기술: "Korea Engineering Consultants Corp.",
  코스맥스비티아이: "COSMAX BTI, INC.",
  그린케미칼: "GREEN CHEMICAL CO.,LTD.",
  현대바이오: "HYUNDAI BIOSCIENCE CO., LTD.",
  세동: "SAE DONG CO. LTD",
  코렌텍: "Corentec Co., Ltd.",
  상상인: "Sangsangin Co., Ltd.",
  광진실업: "KwangjinInd",
  TJ미디어: "TJ MEDIA CO.,LTD",
  피플바이오: "PeopleBio, Inc.",
  신성델타테크: "SHINSUNG DELTA TECH CO., LTD",
  하이딥: "HiDeep Inc.",
  한솔로지스틱스: "Hansol Logistics CO., Ltd",
  알체라: "Alchera Inc.",
  KEC: "KEC CORPORATION",
  CMG제약: "CMG Pharmaceutical Co., Ltd.",
  슈프리마에이치큐: "Suprema HQ Inc.",
  진시스템: "Genesystem Co., Ltd",
  새빗켐: "Sebitchem Co., LTD",
  알에프텍: "RFTECH CO., LTD",
  고려제강: "KISWIRE CO.,LTD",
  보락: "BOLAK CO.,LTD",
  한일홀딩스: "HANIL HOLDINGS CO.,LTD.",
  나우코스: "NOWCOS CO., LTD",
  유니슨: "UNISON CO., LTD.",
  대원: "DAEWON CO., LTD.",
  라이온켐텍: "LION CHEMTECH CO., Ltd.",
  유에스티: "UST CO., LTD.",
  KNN: "KOREA NEW NETWORK CORPORATION",
  디에이테크놀로지: "DA Technology Co.,Ltd.",
  지란지교시큐리티: "Jiransecurity Co., Ltd.",
  삼목에스폼: "SAMMOK S-FORM CO.,LTD.",
  코위버: "COWEAVER Co.,Ltd.",
  파커스: "PAKERS CO., Ltd.",
  큐로홀딩스: "CUROHOLDINGS Co., Ltd.",
  서암기계공업: "SEOAM MACHINERY INDUSTRY CO., LTD",
  젬백스: "GemVax & KAEL Co.,Ltd.",
  신신제약: "SINSIN PHARMACEUTICAL Co., LTD.",
  케이피티유: "Korea Plasma Technology U Co.,Ltd",
  유성티엔에스: "YOOSUNG T&S CO.,LTD",
  블루콤: "BLUECOM CO.,LTD",
  GH신소재: "GH Advanced Materials Inc.",
  "3S": "3S KOREA CO., LTD",
  코맥스: "COMMAX Co., Ltd.",
  서울전자통신: "SEOUL ELECTRONICS & TELECOM",
  이원컴포텍: "EWON COMFORTECH CO.,LTD",
  JW신약: "JW SHINYAK CORPORATION",
  메디아나: "MEDIANA Co.,LTD",
  케이엘넷: "KL-Net Corp.",
  금강철강: "KEUM KANG STEEL CO., LTD",
  대정화금: "Daejung Chemicals & Metals Co., Ltd",
  대륙제관: "DaeryukCan",
  이퓨쳐: "e-future.Co.,Ltd.",
  국일제지: "KUK-IL PAPER MFG CO.,LTD",
  이씨에스: "ECSTELECOMCo.,Ltd.",
  대한과학: "DAIHAN SCIENTIFIC CO., Ltd",
  NE능률: "NE Neungyule, Inc.",
  디에스케이: "DSK Co.,Ltd.",
  유니포인트: "UNIPOINT Corp.",
  케어룸의료산업: "KAREROOM MEDICAL EQUIPMENT CO.,LTD.",
  성창오토텍: "SUNGCHANG AUTOTECH CO.,LTD.",
  영신금속: "YoungSin Corp.",
  YTN: "YTN",
  한일네트웍스: "HANIL NETWORKS CO., LTD.",
  대동금속: "DaedongMetal",
  프럼파스트: "PLUMB FAST CO., LTD.",
  피제이전자: "PJ ELECTRONICS CO., LTD.",
  셀루메드: "CELLUMED CO., LTD.",
  티엘아이: "TLIInc.",
  손오공: "SONOKONGCO.,LTD.",
  알톤스포츠: "altonsports,inc",
  남화토건: "Nam Hwa Construction Company, Limited",
  삼영이엔씨: "Samyung ENC Co., Ltd.",
  삼현철강: "SAMHYUN STEEL Co., Ltd",
  인피니트헬스케어: "INFINITT Healthcare Co., Ltd.",
  비디아이: "BDI Co., LTD.",
  마니커에프앤지: "Maniker F&G",
  인베니아: "INVENIA Co.,Ltd.",
  웰크론: "Welcron Company Limited",
  퓨쳐스트림네트웍스: "Futurestream Networks Co., Ltd.",
  이글벳: "Eagle Veterinary Technology Co.,Ltd",
  삼천리자전거: "SAMCHULY BICYCLE CO., LTD",
  배럴: "BARREL Co., Ltd.",
  케이맥: "Korea Materials & Analysis Corp.",
  서연탑메탈: "SEOYON TOPMETAL CO., LTD.",
  차바이오텍: "Chabiotech Co.,Ltd.",
  위닉스: "WINIX INC.",
  오션스톤: "Ocean Stone Corp,.",
  이십일스토어: "21store Co.,Ltd",
  셀트리온제약: "Celltrion Pharm Inc.",
  비씨월드제약: "BCWORLDPHARM Co., Ltd.",
  파멥신: "PharmAbcine Inc.",
  시너지이노베이션: "Synergy Innovation Co., Ltd.",
  에스디생명공학: "SD BIOTECHNOLOGIES CO., LTD.",
  올리패스: "OLIPASS CORPORATION",
  동우팜투테이블: "DONGWOO FARM TO TABLE CO., LTD",
  광림: "KANGLIM Co., LTD.",
  녹십자셀: "GREEN CROSS CELL CORPORATION",
  지엔원에너지: "G Enone Energy Co.,Ltd.",
  디알젬: "DRGEM CORPORATION",
  SV인베스트먼트: "SV INVESTMENT CORPORATION",
  에스에이엠티: "SAMT CO.,LTD.",
  대원모방: "DAEWON WOOL TEXTILE Co., Ltd.",
  미래테크놀로지: "MIRAE TECHNOLOGY, CO., LTD.",
  팜스코: "FARMSCO",
  아이에이: "iA, Inc.",
  다이노나: "DiNonA Inc.",
  에스케이씨에스: "SKCS CO.,LTD.",
  삼익악기: "SAMICK MUSICAL INSTRUMENTS CO.,LTD",
  한세예스24홀딩스: "HANSAE YES24 HOLDINGS CO., LTD",
  티케이케미칼: "TK CHEMICAL CORPORATION",
  케미메디: "KEMIMEDI Co.Ltd",
  지성이씨에스: "ZISUNG ECS CO.,Ltd.",
  유쎌: "YOUCEL Inc",
  에스엘에스: "SLS LTD",
  비엔디생활건강: "B&D Life Health CO.,LTD",
  금호에이치티: "Kumho HT, Inc.",
  금오하이텍: "KUMO HITEC. CO., LTD",
  성우하이텍: "SUNGWOO HITECH CO., LTD",
  기신정기: "KISHIN CORPORATION",
  에코에너지: "eco energy",
  경남은행: "Kyongnam Bank Co., Ltd.",
  동양기전: "DONGYANG PARK CO.,LTD.",
  파인메딕스: "Finemedix Co., Ltd.",
  한컴: "HANCOM INC.",
  NH농우바이오: "NH NONGWOOBIO CO., LTD.",
  KZ정밀: "KZ Precision Corporation",
  화성밸브: "HS VALVE CO., LTD",
  킵스파마: "Keeps Biopharma Inc.",
  도부: "DOBU Inc.",
  오늘이엔엠: "ONEUL E&M co.,Ltd",
  동일스틸럭스: "DONGIL STEELUX CO., LTD.",
  파두: "FADU INC.",
  씨티알모빌리티: "CTR Mobility Co.,Ltd.",
  뉴온: "NUON CO., LTD.",
  이뮨온시아: "ImmuneOncia Therapeutics, Inc.",
  상지건설: "Sangji Construction, Inc.",
  그린광학: "Green Optics Co.,Ltd.",
  삼익제약: "SAMIK PHARM. CO.,LTD.",
  엑셀세라퓨틱스: "Xcell Therapeutics Inc.",
  삼진식품: "Samjinfood Co., Ltd.",
  지구홀딩스: "ZGOO Holdings Co., Ltd.",
  아로마티카: "AROMATICA CO.",
  파라택시스이더리움: "Parataxis Ethereum, Inc.",
  덕양에너젠: "DEOKYANG ENERGEN CORPORATION",
  블랙야크아이앤씨: "BLACK YAK I&C CO.,LTD",
  파수AI: "FASOO AI Co.,Ltd.",
  한양증권: "HANYANG SECURITIES CO.,LTD",
  한국주강: "HANKOOK STEEL CO.,LTD",
  아이엠바이오로직스: "IMBiologics Corp.",
  액스비스: "AXBIS CO.,LTD",
  휴림에이텍: "HYULIM A-TECH Co., Ltd.",
  에이텀: "ATUM CO., LTD.",
  넥써쓰: "NEXUS Co., Ltd.",
  지씨지놈: "GC Genome Corporation",
  뉴엔AI: "NEWEN AI",
  인티큐브: "Inticube Co., Ltd.",
  베뉴지: "VenueG Co.,Ltd.",
  지에프아이: "GFI Co., Ltd",
  씨메스로보틱스: "CMES Robotics Inc.",
  한빛레이저: "HBL Corporation",
  리센스메디컬: "RecensMedical, Inc.",
  엠엑스온: "MX On CORPORATION",
  아이지넷: "Aiji net Inc.",
  에이에프더블류: "A.F.W Co., Ltd",
  캔버스엔: "CANVAS N Co.,Ltd.",
  아우토크립트: "Autocrypt Co., Ltd.",
  한국가구: "KoreaFurniture",
  삼양바이오팜: "Samyang Biopharm Corporation",
  경보제약: "KYONGBO PHARMACEUTICAL CO., LTD.",
  한켐: "HANCHEM CO.,LTD",
  위더스제약: "Withus Pharmaceutical. Co., LTD",
  에이치와이티씨: "HYTC CO., LTD",
  쿼드메디슨: "QuadMedicine Inc.",
  HLB제넥스: "HLB Genex, Inc.",
  에어레인: "Airrane Co., Ltd.",
  세미파이브: "SemiFive Inc.",
  티디에스팜: "TDSPHARM Co., Ltd.",
  케이티알파: "kt alpha Co., Ltd.",
  체시스: "CHASYS Co.,Ltd",
  더핑크퐁컴퍼니: "The Pinkfong Company, Inc.",
  엠오티: "MOT Co., Ltd.",
  삼현: "SAMHYUN CO.,LTD",
  DB증권: "DB Securities Co.,Ltd",
  와이즈버즈: "Wise birds Inc.",
  티엑스알로보틱스: "TXR Robotics Co., Ltd.",
  휴엠앤씨: "HuM&C Co., Ltd.",
  한국첨단소재: "KOREA ADVANCED MATERIALS Co.,Ltd.",
  대호특수강: "dhSteel",
  하이드로리튬: "Hydro Lithium Inc",
  다산솔루에타: "Dasan Solueta Co.,Ltd.",
  국제약품: "Kukje Pharma Co., Ltd.",
  남선알미늄: "NAMSUN ALUMINIUM CO.,LTD",
  미래엔에듀파트너: "MiraeN Edupartner Co., Ltd.",
  머니무브: "MoneyMove Co., Ltd.",
  오션스바이오: "OceansBio Co., Ltd.",
  알파칩스: "Alphachips, Inc.",
  엑스플러스: "Xplus Inc.",
  이스트에이드: "ESTaid Corp.",
  썸에이지: "Thumbage Co., Ltd.",
  일동홀딩스: "ILDONG HOLDINGS CO.,LTD",
  SG글로벌: "SG GLOBAL CO., LTD",
  이엘씨: "ELC Co., Ltd.",
  캐프: "CAP Co.,Ltd.",
  포커스에이아이: "FOCUS AI Co., Ltd.",
  우리바이오: "WOOREE BIO CO., LTD",
  엣지파운드리: "Edge Foundry Co.,Ltd",
  본시스템즈: "BONSYSTEMS Co., Ltd.",
  인스웨이브: "Inswave Co., Ltd.",
  소노스퀘어: "SONO SQUARE CO.,LTD.",
  태원물산: "TAEWONMULSAN CO.,LTD",
  현대퓨처넷: "Hyundai Futurenet Co., Ltd",
  원일티엔아이: "WONILTNI CO., LTD.",
  동국생명과학: "DongKook Life Science Co., Ltd.",
  포니링크: "PonyLink Co., Ltd.",
  KG에코솔루션: "KG Eco Solution Co., Ltd.",
  링크드: "Linked Inc.",
  문배철강: "MOONBAE STEEL CO.,LTD",
  PKC: "PKC Co., Ltd.",
  성문전자: "SUNGMOON ELECTRONICS CO.,LTD",
  탑선: "Topsun co.,Ltd",
  HS애드: "HS Ad Inc.",
  삼양케이씨아이: "Samyang KCI Corporation",
  큐라티스: "Quratis Inc.",
  알피바이오: "RPbio Inc.",
  케이쓰리아이: "K3I. Co., Ltd.",
  팬스타엔터프라이즈: "Panstar Enterprise Co., Ltd.",
  오토앤: "AUTO& Inc.",
  케일럼: "CAELUM Co., Ltd.",
  파인텍: "FINETEK CO., LTD.",
  HLB바이오스텝: "HLB bioStep Co.,Ltd.",
  에스켐: "S-CHEM Co.,Ltd.",
  "백금T&A": "BG T&A Co.",
  유니온바이오메트릭스: "UNION biometrics Co., Ltd.",
  농심홀딩스: "Nongshim Holdings",
  씨앤투스: "CNTUS Co., Ltd",
  HLB파나진: "HLB PANAGENE Co., LTD.",
  동국알앤에스: "DONGKUK REFRACTORIES & STEEL CO., LTD.",
  그리드위즈: "Gridwiz Co.,Ltd",
  프로티나: "PROTEINA CO.,LTD.",
  승일: "SEUNG IL Corporation",
  제이알글로벌리츠: "JR GLOBAL REIT",
  그린생명과학: "GREEN LIFESCIENCE CO., LTD.",
  아티스트컴퍼니: "Artist Company Inc.",
  좋은사람들: "GOOD PEOPLE CO., LTD.",
  웨이비스: "Wavice Inc.",
  바이오스마트: "BioSmart Co., Ltd.",
  와이제이링크: "YJLINK CO.,LTD.",
  오션인더블유: "Ocean In W Co.,Ltd.",
  케이알엠: "Korea Robot Manufacturing Co., Ltd.",
  한컴위드: "Hancom WITH Inc.",
  엑스페릭스: "Xperix Inc.",
  에이텍모빌리티: "ATEC MOBILITY Co., Ltd",
  강동씨앤엘: "KANGDONG C&L co., Ltd",
  비엘팜텍: "BL Pharmtech Corp.",
  이렘: "IREM Co.,Ltd.",
  아이언디바이스: "Iron Device Corp.",
  카티스: "CATIS INC.",
  제이엔비: "JNB Co.,Ltd",
  더라미: "The Lamy Co., Ltd.",
  대진첨단소재: "DAEJIN ADVANCED MATERIALS Inc.",
  솔브레인홀딩스: "Soulbrain Holdings Co., Ltd.",
  쿠쿠홀딩스: "Cuckoo Holdings Co.,Ltd",
  피노: "FINO INC.",
  지에이이노더스: "GA INNODUS CO., LTD.",
  삼기에너지솔루션즈: "SAMKEE ENERGY SOLUTIONS CO.,LTD",
  아모레퍼시픽홀딩스: "AMOREPACIFIC Holdings Corp.",
  "SGC E&C": "SGC E&C Co., Ltd.",
  엠디바이스: "Mdevice Co., Ltd",
  대창솔루션: "DAECHANG SOLUTION CO.,LTD.",
  무림페이퍼: "MOORIM PAPER CO.,LTD",
  사조동아원: "SAJODONGAONE CO.,LTD",
  DB: "DB Inc.",
  아진전자부품: "AJIN ELECTRONIC COMPONENTS CO.,LTD",
  에스앤더블류: "S&W Corporation",
  스튜디오삼익: "Studio Samick Co.,Ltd.",
  한화갤러리아: "HANWHA GALLERIA CORPORATION",
  나래나노텍: "NARAE NANOTECH CORPORATION",
  아티스트스튜디오: "Artist Studio Inc.",
  금강공업: "KUMKANG KIND CO.,LTD",
  인팩: "INFAC CORPORATION",
  대영포장: "DAEYOUNG PACKAGING CO.,LTD",
  LK삼양: "LK SAMYANG CO., LTD",
  동일제강: "DONG IL STEEL MFG CO., LTD",
  영진약품: "YUNGJIN PHARM. CO., LTD",
  오픈놀: "Openknowl Co.,Ltd.",
  셀레믹스: "Celemics, Inc.",
  씨엔알리서치: "C&R Research Inc.",
  CG인바이츠: "CG Invites Co., Ltd.",
  HB인베스트먼트: "HB Investment, Inc.",
  버넥트: "VIRNECT Co., Ltd.",
  경동도시가스: "KYUNGDONG CITY GAS CO.,LTD",
  위메이드맥스: "Wemade Max Co., Ltd.",
  인지소프트: "Inzisoft Co., Ltd.",
  알루코: "ALUKO CO.,LTD",
  한싹: "Hanssak Co., Ltd.",
  그린리소스: "Green Resource Co.,Ltd",
  이월드: "E-WORLD CO.,LTD.",
  메가터치: "Megatouch Co., Ltd",
  코아시아씨엠: "CoAsia CM Co.,Ltd",
  코아스템켐온: "CORESTEMCHEMON Inc.",
  유진테크놀로지: "YUJIN TECHNOLOGY CO.,LTD.",
  소프트센: "SOFTCEN CO., LTD.",
  파로스아이바이오: "Pharos iBio Co., Ltd.",
  우듬지팜: "WooDeumGee Farm Co., Ltd",
  에스엘테라퓨틱스: "SL Therapeutics, Inc.",
  아이톡시: "ITOXI Corp.",
  DSR: "DSR CORP",
  액션스퀘어: "Action Square Co., Ltd.",
  아이윈: "iWIN CO.,LTD",
  케이비아이동국실업: "KBI DONGKOOK IND CO., LTD",
  롯데손해보험: "Lotte Non-Life Insurance Co., Ltd.",
  알비더블유: "RBW Inc.",
  바이오노트: "BioNote, Inc.",
  핌스: "PIMS Inc.",
  신성통상: "SHINSUNG TONGSANG CO.,LTD",
  옵투스제약: "OPTUS Pharmaceutical Co., Ltd.",
  CS: "CS CORPORATION",
  휴맥스홀딩스: "Humax Holdings Co., Ltd",
  써니전자: "SUNNY ELECTRONICS CO.,LTD",
  우성: "WOOSUNG CO., LTD.",
  플레이그램: "Playgram Co., Ltd.",
  신흥: "SHINHUNG CO.,LTD",
  우진플라임: "WOOJIN PLAIMM CO.,LTD",
  에이프로젠: "Aprogen, Inc",
  범양건영: "BUMYANG CONSTRUCTION CO.,LTD",
  하인크코리아: "HaAINC Korea co., ltd.",
  동방아그로: "DONGBANG AGRO CORP",
  동남합성: "DONGNAMCHEMICALCO.,LTE.",
  한국제지: "Hankuk Paper MFG. CO., LTD",
  유니드비티플러스: "UNID btplus Co., Ltd.",
  LS네트웍스: "LS Networks Corporation Limited",
  이삭엔지니어링: "ISAAC Engineering Co., Ltd.",
  커넥트웨이브: "Connectwave Co., Ltd.",
  세진티에스: "SEJIN T.S CO., LTD.",
  유니온: "UNION CORPORATION",
  동양: "TONGYANG Inc",
  신라교역: "SILLA CO.,LTD",
  일성건설: "ILSUNG CONSTRUCTION CO.,LTD",
  아주스틸: "AJUSTEEL CO.,LTD.",
  대한제당: "TS CORPORATION",
  리튬포어스: "Lithium-for-earth Inc",
  이브이파킹서비스: "EVPS Co., Ltd.",
  강원에너지: "KANGWON ENERGY Co., Ltd.",
  와토스코리아: "WATOSCOREACO.,LTD",
  비엘헬스케어: "BL HEALTH CARE",
  아이엠지티: "IMGT Corporation Limited",
  우리엔터프라이즈: "WOOREE ENTERPRISE CO.,LTD",
  샘표식품: "SEMPIO FOODS COMPANY",
  에이루트: "Aroot Co., Ltd.",
  알티캐스트: "Alticast Corporation",
  피씨디렉트: "PC Direct, Inc.",
  동원수산: "DONGWON FISHERIES CO.,LTD",
  라피치: "RAPEECH Co.,Ltd",
  아미노로직스: "AMINOLOGICS CO.,LTD.",
  디와이씨: "DYC CO.,LTD.",
  양지사: "Yangjisa",
  디모아: "DMOA Co., Ltd",
  흥아해운: "HEUNG-A SHIPPING CO.,LTD.",
  엔시트론: "N CITRON, INC.",
  원림: "WONLIM CORPORATION",
  일신석재: "ILSHIN STONE CO.,LTD",
  STX: "STX CORPORATION",
  케이씨에스: "Korea Computer & Systems Inc.",
  골드앤에스: "Gold&S Co.,Ltd",
  크라우드웍스: "CrowdWorks, Inc.",
  얼라인드: "Aligned Genetics, Inc.",
  디알텍: "DRTECH Corporation",
  인포뱅크: "InfoBankCorporation",
  엑스큐어: "Xcure Corp.",
  일신바이오: "ilShinbiobase Co., Ltd.",
  바이오인프라: "BioInfra Co.,Ltd.",
  대성에너지: "DAESUNG ENERGY CO.,LTD",
  씨엔플러스: "CNPLUS Co., Ltd.",
  노보믹스: "Novomics Co., Ltd.",
  하이스틸: "HISTEEL CO., LTD",
  KPX홀딩스: "KPX HOLDINGS CO., LTD.",
  대한제분: "DAEHAN FLOUR MILL CO.,LTD",
  현대에이치티: "HYUNDAI HT CO,LTD.",
  미래아이앤지: "MiraeING.Co.,Ltd.",
  동성케미컬: "DONGSUNG CHEMICAL Co., Ltd.",
  조비: "CHOBI CO.,LTD",
  극동유화: "KUKDONG OIL & CHEMICALS CO.,LTD",
  레이저쎌: "Laserssel Co. Ltd.",
  제일약품: "JEIL PHARMACEUTICAL CO.,LTD",
  쿠쿠홈시스: "CUCKOO HOMESYS CO.,LTD",
  아남전자: "ANAM ELECTRONICS CO.,LTD",
  원익피앤이: "WONIK PNE CO., LTD.",
  고바이오랩: "KoBioLabs, Inc.",
  누리플렉스: "NuriFlex Co.,Ltd.",
  태성: "TAESUNG CO.,LTD.",
  TCC스틸: "TCC STEEL",
  가온칩스: "GAONCHIPS CO., LTD.",
  모비릭스: "MOBIRIX Corporation",
  삼원강재: "SAMWONSTEEL Co.,Ltd.",
  유니온머티리얼: "Union Materials Corp.",
  프롬바이오: "From Bio Co., Ltd.",
  KC코트렐: "KC Cottrell Co., Ltd.",
  해태제과식품: "Haitai Confectionery and Foods Co., Ltd.",
  미래에셋글로벌리츠: "Mirae Asset Global REIT Co., Ltd.",
  다스코: "Development Advance Solution Co., Ltd.",
  아세아: "ASIA HOLDINGS CO.,LTD",
  일진다이아: "ILJIN DIAMOND CO., LTD.",
  깨끗한나라: "KleanNara Co., Ltd.",
  신일전자: "SHINIL ELECTRONICS CO.,LTD",
  진양화학: "CHINYANG CHEMICAL CORPORATION",
  강남제비스코: "KANGNAM JEVISCO CO.,LTD",
  HDC현대EP: "HDC Hyundai Engineering Plastics Co., Ltd.",
  애경케미칼: "AEKYUNG CHEMICAL CO., LTD",
  이연제약: "REYON PHARMACEUTICAL CO., LTD",
  한전산업: "Korea Electronic Power Industrial Development Co., Ltd",
  일승: "IL SEUNG Co., LTD",
  경인양행: "KYUNG-IN SYNTHETIC CORPORATION",
  다올투자증권: "Daol Investment & Securities Co., Ltd.",
  지더블유바이텍: "GW Vitek CO.,LTD.",
  액토즈소프트: "ACTOZ SOFT CO., LTD.",
  디젠스: "Dgenx Co., Ltd.",
  아시아경제: "The Asia Business Daily Co., Ltd.",
  미코바이오메드: "MiCoBioMed Co.,Ltd.",
  "THE E&M": "THE E&M Co., Ltd.",
  TS트릴리온: "TS Trillion Co., Ltd.",
  유신: "Yooshin Engineering Corporation",
  버킷스튜디오: "BUCKET STUDIO Co.,Ltd.",
  티비씨: "TBC",
  광무: "Kwangmu Co.,Ltd.",
  지니틱스: "Zinitix Co.,Ltd.",
  디지틀조선: "DigitalChosun",
  HLB제약: "HLB PHARMACEUTICAL CO., LTD.",
  파나진: "Panagene Inc.",
  엠브레인: "Macromill Embrain Co., Ltd.",
  우리기술투자: "Woori Technology Investment Co., Ltd",
  네오위즈홀딩스: "NEOWIZ HOLDINGS Corporation",
  에프알텍: "FRTEKCO.,LTD.",
  신도기연: "Shindo Eng. Lab., Ltd.",
  FSN: "FSN Co., Ltd.",
  넥스턴바이오: "NEXTURN Bio Inc.",
  베른: "VERNE INC.",
  씨엔티드림: "CNT Dream CO. LTD.",
  위드텍: "WITHTECH, Inc.",
  동일산업: "DONGIL INDUSTRIES CO.,LTD",
  고려제약: "KOREAN DRUG CO., LTD.",
  이오플로우: "EOFlow Co., Ltd.",
  대성미생물: "Daesung Microbiological Labs. Co. Ltd",
  프레스티지바이오파마: "Prestige BioPharma Limited",
  포인트엔지니어링: "POINT ENGINEERING Co., Ltd.",
  안랩: "AHNLAB,INC.",
  인바이오: "ENBIOCO., LTD.",
  윈텍: "WINTECH.CO.,LTD",
  우원개발: "Woowon Development Co., Ltd.",
  퀀타매트릭스: "QuantaMatrix Incorporated",
  프레스티지바이오로직스: "Prestige Biologics Co., Ltd.",
  아이컴포넌트: "i-Components Co., Ltd",
  디딤: "Didim Inc.",
  투비소프트: "TOBESOFT Co., Ltd.",
  SDN: "SDN Company Ltd.",
  카스: "Cas",
  화신정공: "HWASHIN PRECISION CO., LTD.",
  넷게임즈: "NAT GAMES CO.,LTD",
  엘디티: "LDTInc.",
  모베이스전자: "MOBASE ELECTRONICS CO.,LTD.",
  오성첨단소재: "OSUNG ADVANCED MATERIALS CO., LTD.",
  모헨즈: "Mohenz. Co., Ltd",
  이그잭스: "exax Inc.",
  원일특강: "WonilSpecialSteel",
  알에프세미: "RFsemiTechnologies,Inc.",
  "CSA 코스믹": "CSA COSMIC CO., LTD.",
  진매트릭스: "GENEMATRIX INC.",
  미래에셋맵스리츠: "Miraeasset Maps REIT 1 Co., Ltd.",
  프리엠스: "FreeMs Corporation",
  하이텍팜: "HIGH TECH PHARM CO.,LTD.",
  폭스소프트: "foxSoft Co., Ltd.",
  에너토크: "ENERTORK LTD.",
  지엔코: "Great New wave Coming Co., Ltd.",
  삼아제약: "Sam-A Pharm. Co. Ltd",
  스페코: "Speco",
  파루: "PARU CO., LTD.",
  코미팜: "KOMIPHARM INTERNATIONAL CO., LTD.",
  대동기어: "DaedongGear",
  메디콕스: "MEDICOX Co., Ltd.",
  신원종합개발: "ShinwonConstruction",
  KTcs: "ktcs corporation",
  원익큐브: "WONIK CUBE Corp.",
  위즈코프: "WIZ CORP, Inc.",
  이엑스티: "Ext Co,.Ltd",
  넥스턴: "Nextern Co., Ltd.",
  동양물산: "DONG YANG. CO,. LTD",
  신라에스지: "SILLA SG CO., LTD.",
  진바이오텍: "GeneBioTechCo.,Ltd.",
  삼일기업공사: "SAMIL ENTERPRISE CO., LTD.",
  해성산업: "Haesung Industrial Co., Ltd.",
  에스티큐브: "STCUBE",
  상신전자: "SANGSHIN ELECTRONICS CO., LTD.",
  스타플렉스: "STARFLEX CO., LTD",
  멜파스: "Melfas Inc.",
  한국큐빅: "CUBIC KOREA INC.",
  세중: "SEJOONG CO., LTD.",
  맥스로텍: "MAXROTEC CO., LTD.",
  삼원테크: "SAMWONTECH CO., LTD",
  정원엔시스: "ZUNGWON EN-SYS INC.",
  풍국주정: "Pungguk Ethanol Co.,Ltd.",
  한국테크놀로지: "HANKOOK Technology Inc.",
  아주IB투자: "AJU IB INVESTMENT CO., LTD.",
  에이치엔티: "H&T CO.,LTD",
  씨유메디칼: "CU MEDICAL SYSTEMS Inc.",
  수산아이앤티: "SOOSAN INT Co., LTD.",
  린드먼아시아: "Lindeman Asia Investment Corporation",
  휴럼: "Hurum Co., Ltd.",
  바이오프로테크: "BIO PROTECH INC.",
  구스앤홈: "GOOSE & HOME Co., Ltd",
  장원테크: "JangWonTech Co., Ltd.",
  시스웍: "SYSWORK CO., LTD",
  코센: "KOCEN.CO.LTD",
  엘엠에스: "LMS Co.,Ltd.",
  중앙에너비스: "Joong Ang Enervis Co.,Ltd.",
  삼화왕관: "SAMHWA CROWN & CLOSURE CO.,LTD",
  디케이디앤아이: "DKD&I",
  헬릭스미스: "Helixmith Co., Ltd",
  키네마스터: "KineMaster Corporation",
  신풍제약: "SHINPOONG PHARMACEUTICAL CO.,LTD",
  유안타증권: "Yuanta Securities Korea Co., Ltd.",
  한화투자증권: "HANWHA INVESTMENT&SECURITIES CO.,LTD",
  드림어스컴퍼니: "Dreamus Company",
  유니켐: "UNICHEM CO.,LTD",
  동방: "DONGBANG TRANSPORT & LOGISTICS CO.,LTD",
  신송홀딩스: "SINGSONGHOLDINGS",
  주노콜렉션: "JUNO COLLECTION CO.,LTD",
  파마리서치바이오: "PHARMARESEARCH BIO Co., Ltd.",
  태광산업: "TAEKWANG INDUSTRIAL CO.,LTD",
  원익테라세미콘: "WONIK TERA SEMICON CO.,LTD.",
  스페이스솔루션: "SPACE SOLUTION INC.",
  드림티엔터테인먼트: "Dream T Entertainment Co., Ltd.",
  헝셩그룹: "HENG SHENG HOLDING GROUP COMPANY LIMITED",
  테라젠이텍스: "THERAGEN ETEX CO.,LTD.",
  삼호: "SAMHO CO.,LTD",
  다이오진: "DIOGENE CO., LTD",
  닉스테크: "NICSTECH CO., LTD",
  극동자동화: "Kukdong Automation",
  엠앤씨생명과학: "M&C Life Science Co., Ltd.",
  에스와이제이: "SYJ Co., Ltd.",
  대원화성: "DAEWON CHEMICAL CO.,LTD",
  흥국화재: "Heungkuk Fire & Marine Insurance Co., Ltd.",
  웅진에너지: "Woongjin Energy Co., Ltd",
  디엠씨: "DMC Co",
  켐온: "CHEMON Inc.",
  에이치엘비: "Hue Leisure & Business",
  다린: "DARIN CO.,LTD.",
  동부건설: "Dongbu Corporation",
  휴온스글로벌: "Huons Global Co., Ltd.",
  오가닉티코스메틱: "ORGANIC TEA COSMETICS HOLDINGS COMPANY LIMITED",
  골든센츄리: "ju sikhoesa gold센츄리",
  동아에스텍: "DONG-A S.TECH CO., LTD",
  삼영무역: "SAMYUNG TRADING CO.,LTD",
  태양금속: "TAEYANGMETAL.CO.,LTD",
  에스엔텍: "SN TECH CO.,LTD.",
  에스에너지: "S-EnergyCO.,LTD.",
  보해양조: "BOHAE BREWERY CO.,LTD",
  로스웰: "ROTHWELL INTERNATIONAL CO., LIMITED",
  삼정펄프: "SAM JUNG PULP CO.,LTD.",
  모나리자: "MONALISA CO.,LTD",
  사조오양: "OYANG CORPORATION",
  진도: "JINDO.CO.,LTD",
  코다코: "KODACO CO., LTD",
  인지컨트롤스: "INZI CONTROLS CO.,LTD",
  한국티씨엠: "hanguktcm",
  케이탑리츠: "K-TOP REITS CO.,LTD.",
  대유에이텍: "DAYOU AUTOMOTIVE SEAT-TECHNOLOGY CO.,LTD",
  아이진: "EyeGene,Inc",
  대동고려삼: "DAEDONG KOREA GINSENG CO.,LTD.",
  디와이엘엔제이: "DYLNJ Co., Ltd",
  디피앤케이: "Design Power & Korea Co., Ltd.",
  네오위즈인터넷: "NEOWIZ INTERNET Corporation",
  디오텍: "won bang cast iron co.,ltd",
  우리투자증권: "Woori Investment Securities Co., Ltd.",
  에이씨티: "Axia Creative Tech Co.,Ltd",
  지디: "Global Display Co., Ltd.",
  현대비앤지스틸: "HYUNDAI BNG STEEL CO., LTD",
  신원: "SHINWON CORPORATION",
  신일제약: "SHINIL PHARMACEUTICAL CO., LTD.",
  온미디어: "ON*Media Corporation",
  케이아이씨: "KIC CO.,LTD",
};
/* ── DART 자동 채움 끝 ── */

/* ── 사명변경 자동 채움 시작 · scripts/fill-subjects-from-renames.mjs 가 만든다 ──
 *
 * ⚠ **일부러 비워 둔다.** 채울 수 있는데 안 채우는 것이다.
 *
 * 2026-08-04, 주식시세 아카이브를 받고 나서 **사명이 바뀐 299종목(1,034건)을
 * 채울 수 있게 됐다.** 커버리지가 98.00% → 99.56% 로 오른다.
 * `npm run subjects:renames` 로 언제든 다시 잴 수 있다.
 *
 * **그런데 채우지 않기로 했다.** 이유가 둘이다.
 *
 *   ① 그 값은 「현재 법인명」이라 **시점이 다르다.**
 *      2018년 「아주캐피탈」 리포트에 `WOORI FINANCIAL CAPITAL` 이 붙는다.
 *      법인은 같지만 그 리포트가 다룬 회사의 그때 이름이 아니다.
 *
 *   ② ⭐ **우리가 이미 공개한 명세에 반한다.** `/v1/meta` 가 이렇게 말한다 —
 *      "Historical Korean names are kept as filed — a 2014 report on Daewoo
 *       Shipbuilding is not relabelled with the 2026 corporate name."
 *      이용자에게 한 약속이다. **조용히 바꾸면 명세가 거짓이 된다.**
 *      커버리지 1.5%p 와 바꿀 것이 아니다.
 *
 * 나중에 정말 필요하면 `subjectEn` 을 바꾸지 말고 **별도 필드**로 낸다
 * (예: `subjectEnCurrent` + 명세 갱신). 같은 칸에 다른 뜻을 넣지 않는다.
 *
 * ⚠ **이 선언은 지우지 않는다.** `describeSubject` 가 참조한다.
 */
export const RENAMED_SUBJECTS = {};
/* ── 사명변경 자동 채움 끝 ── */

/**
 * 한글 종목명을 영문으로 편다.
 * **사전에 없으면 null 이다 — 추측하지 않는다.**
 */
export function describeSubject(ko) {
  if (!ko) return null;
  /*
   * ⚠ 순서가 뜻을 갖는다. **손으로 확인한 사전이 먼저다.**
   *   DART 는 「법인명」이라 종목 표기와 다를 수 있고(주식회사·(주) 등),
   *   사람이 고른 표기가 더 정확한 경우가 있다.
   *   실제로 두 곳이 갈린다 — 우리는 `GS E&C`, DART 는 `GS Engineering & Construction`.
   *   짧은 통용 표기를 쓴다는 편집 판단이므로 손 사전이 이긴다.
   */
  /*
   * ⚠ 사명변경은 **맨 뒤**다. 여기 값은 「현재 법인명」이라 시점이 다를 수 있다 —
   *   2018년 「아주캐피탈」에 `WOORI FINANCIAL CAPITAL` 이 붙는다. 법인은 같다.
   *   앞의 둘에 있으면 그게 그 이름 그대로의 표기이므로 먼저 쓴다.
   */
  return SUBJECTS[ko] ?? DART_SUBJECTS[ko] ?? RENAMED_SUBJECTS[ko] ?? null;
}

/** 사전 통계. `/v1/meta` 가 쓴다. */
export const SUBJECT_STATS = {
  /** 손으로 확인한 것 + DART 자동 */
  entries: Object.keys(SUBJECTS).length + Object.keys(DART_SUBJECTS).length,
  curated: Object.keys(SUBJECTS).length,
  fromDart: Object.keys(DART_SUBJECTS).length,
  /**
   * 실측 커버리지 — 아카이브 66,105건 중 영문이 나가는 비율.
   * 2026-08-04 KST: DART `corp_eng_name` 을 붙여 **86.1% → 97.9%**.
   * 남은 2.1%(384종목)는 사명이 바뀌었거나 상장폐지된 회사다.
   * ⚠ 그건 **일부러 안 채운다.** 2014년 리포트의 「대우조선해양」을 2026년 사명으로
   *   부르면 기록이 아니라 왜곡이다.
   */
  coveragePct: 97.9,
  note: 'Curated by report frequency, then filled from DART corp_eng_name (the English name each company filed with the regulator). Names not in the dictionary return null rather than a guess.',
};
